import{connection,ask}from'../ai-client.js';
const $=id=>document.getElementById(id),colors=['#d5fa74','#7edaff','#f9a6d8'];
const funcs=new Set(['sin','cos','tan','asin','acos','atan','sqrt','abs','log','log10','exp','floor','ceil','round','min','max']);
function normalize(s){return s.trim().replace(/^[yY]\s*=/,'').replace(/[×·]/g,'*').replace(/÷/g,'/').replace(/[−–]/g,'-').replace(/π/g,'pi').replace(/²/g,'^2').replace(/³/g,'^3')}
function compile(s){s=normalize(s);if(!s||s.length>300)throw Error('Enter an expression of up to 300 characters.');let node=math.parse(s),count=0;node.traverse(n=>{if(++count>100)throw Error('Please simplify this expression.');if(!['OperatorNode','ConstantNode','SymbolNode','FunctionNode','ParenthesisNode'].includes(n.type))throw Error('Use numbers, x, arithmetic, parentheses, and standard math functions.');if(n.isOperatorNode&&!['+','-','*','/','^','%'].includes(n.op))throw Error('This operator is not supported.');if(n.isSymbolNode&&!['x','pi','e',...funcs].includes(n.name))throw Error('Unknown symbol: '+n.name);if(n.isFunctionNode&&!funcs.has(n.fn.name))throw Error('Unsupported function.');if(n.isConstantNode&&typeof n.value!=='number')throw Error('Use numeric values.');});let c=node.compile();return x=>{let v=c.evaluate({x});return typeof v==='number'&&Number.isFinite(v)?v:NaN}}
function fmt(v){return Number.isFinite(v)?Number(v.toPrecision(10)).toString():'undefined'}
function solve(s){let parts=s.split('=');if(parts.length!==2||parts.some(s=>!s.trim()))throw Error('Enter one equation, such as 2x + 3 = 11.');let a=compile(parts[0]),b=compile(parts[1]),f=x=>a(x)-b(x);if([-99.37,-1.231,0,2.719,97.137].every(x=>Math.abs(f(x))<1e-12))throw Error('The sides appear equal throughout this range; there may be infinitely many solutions.');let roots=[],add=x=>{if(Math.abs(f(x))<1e-7&&!roots.some(r=>Math.abs(r-x)<1e-5))roots.push(x)};let left=-100,fl=f(left);add(left);for(let i=1;i<=4000;i++){let right=-100+i*.05,fr=f(right);if(Number.isFinite(fr)&&Number.isFinite(fl)&&fr*fl<0){let l=left,r=right,v=fl;for(let j=0;j<55;j++){let mid=(l+r)/2,m=f(mid);if(!Number.isFinite(m))break;if(v*m<=0)r=mid;else{l=mid;v=m}}add((l+r)/2)}add(right);left=right;fl=fr}return roots.sort((a,b)=>a-b)}
$('calculate').onclick=()=>{try{let s=normalize($('expression').value),answer;if(s.includes('=')){let roots=solve(s);answer=roots.length?'x ≈ '+roots.map(fmt).join(', '):'No roots found';$('calcStatus').textContent='Numerical search: −100 ≤ x ≤ 100. May miss touching or closely spaced roots; not a proof of all solutions.'}else{if(/\bx\b/.test(s)||/\dx/.test(s))throw Error('Use Graph this for an expression with x, or enter an equation.');let v=compile(s)(0);if(!Number.isFinite(v))throw Error('Result is undefined in the real numbers.');answer=fmt(v);$('calcStatus').textContent=''}$('answer').textContent=answer;let li=document.createElement('li');li.textContent=s+' → '+answer;$('calcHistory').prepend(li);while($('calcHistory').children.length>10)$('calcHistory').lastChild.remove()}catch(e){$('answer').textContent='—';$('calcStatus').textContent=e.message}};
$('expression').onkeydown=e=>{if(e.key==='Enter')$('calculate').click()};
for(let key of ['7','8','9','/','4','5','6','*','1','2','3','-','0','.','(',')','sin(','sqrt(','^','+','pi','C','⌫','=']){let b=document.createElement('button');b.textContent=key;b.onclick=()=>{let i=$('expression');if(key==='=')return $('calculate').click();if(key==='C')i.value='';else if(key==='⌫'){let pos=i.selectionStart;i.setRangeText('',pos===i.selectionEnd?Math.max(0,pos-1):pos,i.selectionEnd,'end')}else i.setRangeText(key,i.selectionStart,i.selectionEnd,'end');i.focus()};$('keypad').append(b)}
let curves=[],cx=0,cy=0,span=20;const canvas=$('graph'),ctx=canvas.getContext('2d');let w=800,h=420;
function bounds(){return{left:cx-span/2,right:cx+span/2,bottom:cy-span*h/w/2,top:cy+span*h/w/2}}
function plot(){curves=[];let errors=[];['f1','f2','f3'].forEach((id,i)=>{let s=$(id).value.trim();if(s)try{curves.push({fn:compile(s),color:colors[i],name:'y'+(i+1)})}catch(e){errors.push('y'+(i+1)+': '+e.message)}});$('graphStatus').textContent=errors.join(' · ');draw();table()}
function draw(){let rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;let dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);let b=bounds(),px=x=>(x-b.left)/span*w,py=y=>(b.top-y)/span*w;let raw=span/10,base=10**Math.floor(Math.log10(raw)),step=[1,2,5,10].map(v=>v*base).find(v=>v>=raw);ctx.font='11px Arial';for(let x=Math.ceil(b.left/step)*step;x<=b.right;x+=step){let p=px(x);ctx.strokeStyle='#263533';ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,h);ctx.stroke();ctx.fillStyle='#8b9c97';ctx.fillText(fmt(x),p+4,Math.max(13,Math.min(h-6,py(0)+15)))}for(let y=Math.ceil(b.bottom/step)*step;y<=b.top;y+=step){let p=py(y);ctx.strokeStyle='#263533';ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(w,p);ctx.stroke();ctx.fillStyle='#8b9c97';ctx.fillText(fmt(y),Math.max(4,Math.min(w-48,px(0)+5)),p-4)}ctx.strokeStyle='#6d8279';ctx.beginPath();ctx.moveTo(px(0),0);ctx.lineTo(px(0),h);ctx.moveTo(0,py(0));ctx.lineTo(w,py(0));ctx.stroke();for(let curve of curves){ctx.strokeStyle=curve.color;ctx.lineWidth=2;ctx.beginPath();let prev=null;for(let i=0;i<=w;i++){let y;try{y=curve.fn(b.left+i/w*span)}catch{y=NaN}let p=py(y);if(!Number.isFinite(p)||Math.abs(p)>h*5){prev=null;continue}if(prev===null||Math.abs(p-prev)>h*.8)ctx.moveTo(i,p);else ctx.lineTo(i,p);prev=p}ctx.stroke()}ctx.lineWidth=1}
function table(){let start=Number($('tableX').value);if(!Number.isFinite(start))return;let t=document.createElement('table'),head=document.createElement('tr');for(let name of ['x',...curves.map(c=>c.name)]){let th=document.createElement('th');th.textContent=name;head.append(th)}t.append(head);for(let i=0;i<5;i++){let x=start+i,tr=document.createElement('tr');for(let val of [x,...curves.map(c=>{try{return c.fn(x)}catch{return NaN}})]){let td=document.createElement('td');td.textContent=fmt(val);tr.append(td)}t.append(tr)}$('table').replaceChildren(t)}
$('plot').onclick=plot;$('tableUpdate').onclick=table;let zoom=f=>{span=Math.max(.001,Math.min(1e6,span*f));draw()};$('zoomIn').onclick=()=>zoom(.7);$('zoomOut').onclick=()=>zoom(1/.7);$('resetView').onclick=()=>{cx=cy=0;span=20;draw()};$('toGraph').onclick=()=>{let s=normalize($('expression').value);if(s.includes('=')){let [a,b]=s.split('=');s='('+a+')-('+b+')'}$('f1').value=s;plot();canvas.scrollIntoView({behavior:'smooth',block:'center'})};canvas.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?1.12:1/1.12)};let drag=null;canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,cx,cy};canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.onpointermove=e=>{if(drag){cx=drag.cx-(e.clientX-drag.x)/w*span;cy=drag.cy+(e.clientY-drag.y)/w*span;draw()}let r=canvas.getBoundingClientRect(),b=bounds(),x=b.left+(e.clientX-r.left)/w*span,y=b.top-(e.clientY-r.top)/w*span;$('coords').textContent='x = '+fmt(x)+' · y = '+fmt(y)};new ResizeObserver(draw).observe(canvas);plot();
let base=null,imageData='',ocrPromise=null,photoBusy=false;connection().then(v=>{base=v;$('aiStatus').textContent=base?'AI photo solver connected. Check its interpretation and result.':'AI photo solving is not connected yet. Printed-text reading and the calculator are available.';$('solvePhoto').disabled=!base||!imageData});
$('photo').onchange=async()=>{imageData='';$('readPhoto').disabled=$('solvePhoto').disabled=true;$('preview').hidden=true;$('photoAnswer').textContent='';$('recognized').value='';let f=$('photo').files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>10*1024*1024){$('photoStatus').textContent='Choose a JPG, PNG, or WebP smaller than 10 MB.';return}try{let bitmap=await createImageBitmap(f),scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=bitmap.width*scale;c.height=bitmap.height*scale;c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();imageData=c.toDataURL('image/jpeg',.9);$('preview').src=imageData;$('preview').hidden=false;$('readPhoto').disabled=false;$('solvePhoto').disabled=!base;$('photoStatus').textContent='Picture ready. Choose printed-text reading or AI solving.'}catch{$('photoStatus').textContent='This picture could not be opened. Try another file.'}};
function loadOCR(){if(!ocrPromise)ocrPromise=new Promise((resolve,reject)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>{ocrPromise=null;reject(Error('Text reader could not download. Check your connection or type the expression.'))};document.head.append(s)});return ocrPromise}
async function photoTask(ai){if(photoBusy||!imageData)return;photoBusy=true;$('photo').disabled=true;$('readPhoto').disabled=$('solvePhoto').disabled=true;let worker;try{if(ai){$('photoStatus').textContent='Reading and solving your picture…';$('photoAnswer').textContent=await ask(base,{mode:'photo',image:imageData,problem:'Read the pictured problem and solve it. If unclear, ask for a clearer photo.'})}else{$('photoStatus').textContent='Loading text reader…';await loadOCR();worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status)$('photoStatus').textContent=m.status+' '+Math.round((m.progress||0)*100)+'%'}});let r=await worker.recognize(imageData);$('recognized').value=r.data.text.trim();if(!$('recognized').value)throw Error('No text found. Try a brighter, closer photo.')} $('photoStatus').textContent=ai?'AI result — verify the transcribed problem.':'Review the recognized text, especially signs and exponents, before using it.'}catch(e){$('photoStatus').textContent=e.message}finally{if(worker)await worker.terminate();photoBusy=false;$('photo').disabled=false;$('readPhoto').disabled=!imageData;$('solvePhoto').disabled=!base||!imageData}}
$('readPhoto').onclick=()=>photoTask(false);$('solvePhoto').onclick=()=>photoTask(true);$('useText').onclick=()=>{let s=$('recognized').value.trim();if(!s){$('photoStatus').textContent='Read a picture or type an expression first.';return}$('expression').value=normalize(s);$('expression').focus();$('expression').scrollIntoView({behavior:'smooth',block:'center'});$('calcStatus').textContent='Review the expression, then click Calculate.'};
