import {loadPopulationSurface,installPopulationSurface} from './population.mjs';
import {dressBoss} from './bosses.mjs';
import {npcPose} from './events.mjs';
import * as T from './vendor/three.module.js';
const V=T.Vector3,M=T.Matrix4,O=T.Object3D;
export function installDetail({scene,hero,head,arms,legs,red,blue,black,buildings,npcs,cars,carBody,carTop,player,renderer}){
 const tmp=new O(), cache=new Map(), detailRoot=new T.Group();scene.add(detailRoot);
 const material=(color,roughness=.65,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
 const steel=material('#637484',.32,.75),concrete=material('#a5abb0'),dark=material('#1b2837',.5,.3),glass=new T.MeshPhysicalMaterial({color:'#7296af',roughness:.14,metalness:.45,clearcoat:1,clearcoatRoughness:.12}),warm=new T.MeshStandardMaterial({color:'#ffe8bc',emissive:'#ffd6a0',emissiveIntensity:.35,roughness:.3}),rubber=material('#141a21',.9),chrome=material('#a4b4c1',.24,.85);
 const unitBox=new T.BoxGeometry(1,1,1);
 function sphere(w=104,h=72){let key=w+','+h;if(!cache.has(key))cache.set(key,new T.SphereGeometry(1,w,h));return cache.get(key);}
 function ell(parent,mat,x,y,z,sx,sy,sz,geo=sphere()){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;parent.add(m);return m;}
 function cube(parent,mat,x,y,z,w,h,d,geo=unitBox){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.scale.set(w,h,d);parent.add(m);m.castShadow=true;m.receiveShadow=true;return m;}
 function tube(parent,points,r=.004,mat=black,segments=8){const curve=new T.CatmullRomCurve3(points);const mesh=new T.Mesh(new T.TubeGeometry(curve,Math.max(16,points.length*3),r,segments,false),mat);parent.add(mesh);return mesh;}
 function batch(parent,geo,mat,items){const m=new T.InstancedMesh(geo,mat,items.length);for(let i=0;i<items.length;i++){const a=items[i];tmp.position.set(a[0],a[1],a[2]);tmp.scale.set(a[3],a[4],a[5]);tmp.rotation.set(a[6]||0,a[7]||0,a[8]||0);tmp.updateMatrix();m.setMatrixAt(i,tmp.matrix);}m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function roundedBox(radius=.12,segments=8){const geo=new T.BoxGeometry(1,1,1,segments,segments,segments),pos=geo.attributes.position;for(let i=0;i<pos.count;i++){const p=new V().fromBufferAttribute(pos,i),core=p.clone().clampScalar(-.5+radius,.5-radius),n=p.clone().sub(core);if(n.lengthSq()>0)p.copy(core).add(n.normalize().multiplyScalar(radius));pos.setXYZ(i,p.x,p.y,p.z);}geo.computeVertexNormals();return geo;}
 const rounded=roundedBox(.13,12),facadeBevel=roundedBox(.06,6);
 // Hero appearance is supplied by the fitted skeletal character.
 // Cubic car silhouettes become rounded bodies, with separately modeled wheels and trim.
 carBody.geometry=rounded;carTop.geometry=roundedBox(.19,14);
 const tireGeo=new T.TorusGeometry(.43,.13,14,40),rimGeo=new T.CylinderGeometry(.32,.32,.07,32,1),lampGeo=roundedBox(.12,6);
 const vehicleParts=[];function carPart(geo,mat,offset,scale,rot=[0,0,0]){const mesh=new T.InstancedMesh(geo,mat,cars.length);mesh.castShadow=true;scene.add(mesh);vehicleParts.push({mesh,offset,scale,rot,spin:geo===tireGeo?'z':geo===rimGeo?'y':null});}
 for(let s of [-1,1])for(let z of [-1.65,1.65]){carPart(tireGeo,rubber,[s*1.25,.64,z],[1,1,1],[0,Math.PI/2,0]);carPart(rimGeo,chrome,[s*1.38,.64,z],[1,1,1],[0,0,Math.PI/2]);}
 for(let s of [-1,1]){carPart(lampGeo,warm,[s*.87,1.05,2.66],[.55,.26,.09]);carPart(lampGeo,material('#d41d33'),[s*.86,1.1,-2.66],[.62,.23,.08]);carPart(rounded,steel,[s*1.4,1.75,.8],[.27,.19,.35]);carPart(unitBox,dark,[s*1.17,1.84,0],[.07,.61,.11]);}
 carPart(lampGeo,chrome,[0,.74,2.66],[2.3,.16,.14]);carPart(lampGeo,chrome,[0,.74,-2.66],[2.3,.16,.14]);carPart(unitBox,dark,[0,1,2.715],[1.1,.25,.025]);carPart(unitBox,material('#d3d8d9'),[0,.88,-2.74],[.45,.16,.025]);
 // Detailed pedestrian rigs are pooled around the player; distant people retain the batched rig.
 const allPeople=[],closePeople=[],skinMats=['#ca9e7a','#855b42','#e0bda2','#5b392c'].map(c=>material(c)),clothMats=['#506a81','#a37063','#496557','#cab999','#363f51'].map(c=>material(c));
 const torsoGeo=new T.LatheGeometry([new T.Vector2(0,-1),new T.Vector2(.70,-.99),new T.Vector2(.86,-.85),new T.Vector2(.88,-.45),new T.Vector2(.97,.1),new T.Vector2(1,.55),new T.Vector2(.90,.76),new T.Vector2(.48,.94),new T.Vector2(.34,1),new T.Vector2(0,1)],160);
 const headGeo=sphere(112,80).clone(),hp=headGeo.attributes.position;for(let i=0;i<hp.count;i++){let x=hp.getX(i),y=hp.getY(i),z=hp.getZ(i);const jaw=.77+.23*T.MathUtils.smoothstep(y,-.9,.15);x*=jaw;if(z>0){z*=.87;const eyes=Math.exp(-Math.pow((Math.abs(x)-.38)/.18,2)-Math.pow((y-.17)/.15,2));z-=eyes*.075;if(y<-.3)z+=.05*(1-Math.abs(x));}hp.setXYZ(i,x,y,z);}headGeo.computeVertexNormals();
 function person(index){const root=new T.Group(),skin=skinMats[index%4],cloth=clothMats[index%5],pants=material('#283543'),hair=material(index%3?'#292523':'#715a42');root.visible=false;scene.add(root);
 const torso=ell(root,cloth,0,1.15,0,.30,.40,.19,torsoGeo);ell(root,cloth,0,1.40,0,.30,.13,.18);ell(root,skin,0,1.52,0,.095,.12,.1);ell(root,skin,0,1.73,0,.18,.245,.185,headGeo);ell(root,hair,0,1.875,-.018,.184,.12,.175);ell(root,skin,0,1.71,.175,.042,.061,.053);ell(root,skin,0,1.60,.12,.08,.05,.054);for(let s of[-1,1]){ell(root,skin,s*.18,1.74,0,.038,.066,.03);ell(root,material('#ece9e3'),s*.067,1.775,.165,.039,.022,.019,sphere(24,16));ell(root,dark,s*.067,1.773,.181,.012,.014,.006,sphere(20,12));cube(root,cloth,s*.155,1.32,.185,.115,.10,.013);}
 tube(root,[new V(0,1.46,.178),new V(0,1.23,.20),new V(0,.9,.14)],.004,chrome,6);
 const limbs=[],elbows=[],knees=[];for(let s of[-1,1]){const a=new T.Group();a.position.set(s*.345,1.4,0);root.add(a);ell(a,cloth,0,-.18,0,.105,.23,.11);const elbow=new T.Group();elbow.position.y=-.35;a.add(elbow);elbows.push(elbow);ell(elbow,cloth,0,-.15,0,.085,.19,.085);ell(elbow,skin,0,-.35,.015,.068,.10,.043);for(let f=0;f<4;f++)ell(elbow,skin,(f-1.5)*.027,-.42,.015,.012,.045,.014,sphere(40,24));limbs.push(a);const l=new T.Group();l.position.set(s*.15,.9,0);root.add(l);ell(l,pants,0,-.22,0,.133,.25,.14);const knee=new T.Group();knee.position.y=-.43;l.add(knee);knees.push(knee);ell(knee,pants,0,-.19,0,.104,.22,.11);ell(knee,rubber,0,-.38,.09,.13,.09,.24);cube(knee,chrome,0,-.44,.09,.24,.025,.39,rounded);limbs.push(l);}
 // Sewn collars, jacket seams, cuffs and modeled shoe laces.
 for(const side of[-1,1]){const collar=cube(root,cloth,side*.09,1.48,.135,.10,.12,.026,rounded);collar.rotation.z=side*.5;for(let j=0;j<4;j++)ell(root,chrome,.025,1.34-j*.11,.20,.009,.009,.007,sphere(16,12));const k=knees[side===-1?0:1];for(let j=0;j<5;j++)tube(k,[new V(-.07,-.34,.09+j*.018),new V(.07,-.34,.11+j*.018)],.004,cloth,6);}
 const vest=new T.Group();root.add(vest);cube(vest,dark,0,1.17,.19,.48,.43,.08,rounded);for(let side of[-1,1]){cube(vest,dark,side*.23,1.36,.05,.075,.30,.25,rounded);for(let j=0;j<3;j++)cube(vest,cloth,side*.12,1.05+j*.10,.245,.17,.065,.055,rounded);}vest.visible=false;
 const slots=[];root.traverse(o=>{if(o.isMesh){const role=o.material===cloth?'cloth':o.material===skin?'skin':o.material===pants?'pants':o.material===hair?'hair':null;if(role)slots.push({mesh:o,role});}});
 const webWrap=new T.Group();root.add(webWrap);const webM=new T.MeshStandardMaterial({color:'#e0edf1',roughness:.6});for(let j=0;j<7;j++){const band=new T.Mesh(new T.TorusGeometry(.34,.012,5,28),webM);band.rotation.x=Math.PI/2;band.scale.y=.65;band.position.y=.7+j*.11;webWrap.add(band);}webWrap.visible=false;const bodyMeshes=slots.filter(s=>s.role!=='hair'&&(s.mesh.geometry===torsoGeo||s.mesh.geometry===sphere())&&s.mesh.getWorldPosition(new V()).y<1.51).map(s=>s.mesh);
 // Human proportions: shrink the face ensemble together, retaining its modeled features.
 for(const o of root.children)if(o.isMesh&&o.position.y>1.51){o.position.x*=.7;o.position.y=1.64+(o.position.y-1.73)*.70;o.position.z*=.7;o.scale.multiplyScalar(.70);}
 const rig={root,limbs,elbows,knees,webWrap,index:-1,torso,slots,vest,bodyMeshes};allPeople.push(rig);return rig;}
 for(let i=0;i<20;i++)closePeople.push(person(i));
 const looks=new WeakMap();function applyAppearance(p,n){let look=looks.get(n);const key=[n.shirt,n.color,n.hostile,n.boss?.id].join(':');if(!look||look.key!==key){look={key,cloth:material(n.boss?.color||(n.hostile?'#702936':n.shirt||'#d4a03c')),skin:material(n.boss&&['rhino','shocker','scorpion','venom'].includes(n.boss.id)?n.boss.color:n.color||'#ca9e7a'),pants:material(n.boss?.color||n.pants||'#27364a'),hair:material(n.hair||'#292523')};looks.set(n,look);}if(p.appearance!==look){for(const slot of p.slots)slot.mesh.material=look[slot.role];p.appearance=look;p.vest.visible=n.hostile&&!n.boss;}p.actor=n;if(p.surface){const pal=p.surface.material.userData.palette;pal.cloth.value.copy(look.cloth.color);pal.skin.value.copy(n.boss&&['rhino','shocker','scorpion','venom'].includes(n.boss.id)?look.cloth.color:look.skin.color);pal.pants.value.copy(look.pants.color);}}
 const bossRigs=npcs.filter(n=>n.boss).map((n,i)=>{const p=person(i);applyAppearance(p,n);dressBoss(p,n.boss,{ell,cube,tube,material,sphere,rounded});return {n,p};});
 const ready=loadPopulationSurface().then(geometry=>{for(const p of allPeople){installPopulationSurface(p,geometry);applyAppearance(p,p.actor||{shirt:'#d4a03c',color:'#ca9e7a'});}});
 function posePerson(p,n,time,world=true){const pose=npcPose(n,time);p.animateBoss?.(time,n);if(world)p.root.position.copy(n.p);else p.root.position.set(0,0,0);p.root.position.y+=pose.bob;p.root.rotation.set(pose.lean,n.dir||0,pose.roll);
 for(let i=0;i<2;i++){p.limbs[i*2].rotation.set(pose.arms[i],0,pose.armZ[i]);p.limbs[i*2+1].rotation.set(pose.legs[i],0,0);p.elbows[i].rotation.set(pose.elbows[i],0,0);p.knees[i].rotation.set(pose.knees[i],0,0);}p.webWrap.visible=pose.bound>0;p.webWrap.scale.setScalar(Math.max(.001,pose.bound));
 }
 function createPassenger(container){for(const child of [...container.children])child.visible=false;const rig=person(3);container.add(rig.root);rig.root.visible=true;applyAppearance(rig,{shirt:'#d4a03c',color:'#ca9e7a',hair:'#715a42'});return rig;}
 function updatePeople(time,quality){const count=quality==='ultra'?20:quality==='high'?12:6,range=quality==='ultra'?100:quality==='high'?70:40;
 const nearby=npcs.map((n,i)=>({n,i,d:n.p.distanceToSquared(player.p)})).filter(o=>!o.n.boss&&o.d<range*range).sort((a,b)=>(a.n.event?-10000:0)+a.d-((b.n.event?-10000:0)+b.d)).slice(0,count);for(const n of npcs)n.detailed=false;
 for(let j=0;j<closePeople.length;j++){const p=closePeople[j],o=nearby[j];p.root.visible=!!o;if(!o)continue;const n=o.n;n.detailed=true;applyAppearance(p,n);posePerson(p,n,time);}
 for(const {n,p}of bossRigs){p.root.visible=n.p.distanceTo(player.p)<550; n.detailed=true;if(p.root.visible)posePerson(p,n,time);}
 }
 // Near-building geometry is streamed in bounded pools.
 const buildingDetails=new Map();let detailTick=0;
 function makeBuilding(b){const root=new T.Group();root.position.set(b.x,0,b.z);detailRoot.add(root);const frames=[],panes=[],floorEdges=[],roofRail=[],entry=[];const colsX=Math.max(3,Math.floor(b.w/5.5)),colsZ=Math.max(3,Math.floor(b.d/5.5)),floors=Math.floor(b.h/4.2);
 for(let side=0;side<4;side++){const width=side<2?b.w:b.d,cols=side<2?colsX:colsZ,depth=side<2?b.d:b.w;for(let c=0;c<=cols;c++){let u=-width/2+c*width/cols;if(side<2)frames.push([u,b.h/2,(side===0?1:-1)*(depth/2+.22),.16,b.h,.45]);else frames.push([(side===2?1:-1)*(depth/2+.22),b.h/2,u,.45,b.h,.16]);}
 for(let f=1;f<floors;f++){let yy=f*4.2;if(side<2)floorEdges.push([0,yy,(side===0?1:-1)*(depth/2+.3),width,.16,.6]);else floorEdges.push([(side===2?1:-1)*(depth/2+.3),yy,0,.6,.16,width]);}
 for(let f=1;f<floors;f++)for(let c=0;c<cols;c++){const u=-width/2+(c+.5)*width/cols,yy=f*4.2+1.75;if(side<2)panes.push([u,yy,(side===0?1:-1)*(depth/2+.08),width/cols-.28,3.3,.075]);else panes.push([(side===2?1:-1)*(depth/2+.08),yy,u,.075,3.3,width/cols-.28]);}
 }
 batch(root,facadeBevel,steel,frames);batch(root,facadeBevel,steel,floorEdges);batch(root,unitBox,glass,panes);
 // Layered masonry sills, fire escapes, street-level storefronts and cornices.
 const sills=[],escape=[];for(let floor=1;floor<Math.min(floors,15);floor++){const y=floor*4.2;for(let c=0;c<colsX;c++)sills.push([-b.w/2+(c+.5)*b.w/colsX,y-.12,b.d/2+.38,b.w/colsX-.12,.23,.85]);if(b.style!==2){escape.push([b.w*.28,y+1.4,b.d/2+1.4,5,.16,2.4]);escape.push([b.w*.28,y+2,b.d/2+2.5,5,.08,.08]);for(let j=0;j<12;j++)escape.push([b.w*.28-1.8+j*.30,y+.9-j*.33,b.d/2+1.5,.34,.10,1.8]);}}batch(root,facadeBevel,concrete,sills);batch(root,unitBox,steel,escape);
 const canopy=material(['#405758','#75453e','#243a57','#69624d'][b.style]);for(let c=-2;c<=2;c++){const x=c*(b.w/5);cube(root,canopy,x,4.5,b.d/2+1.8,b.w/5-1,.3,3.6,rounded);cube(root,glass,x,2.3,b.d/2+.32,b.w/5-1.6,3.7,.12);cube(root,chrome,x,2.3,b.d/2+.42,.075,3.7,.14);}for(let j=0;j<3;j++)cube(root,concrete,0,b.h-1.5+j*.5,0,b.w+.4+j*.3,.22,b.d+.4+j*.3,rounded);

 // Deep entrance portal, canopy, lobby doors and steps.
 const front=b.d/2;for(let s of[-1,1])entry.push([s*5,3.4,front+.75,.8,6.8,2]);entry.push([0,6.7,front+1,11,.6,3]);entry.push([0,4.9,front+3,15,.28,7]);for(let k=0;k<3;k++)entry.push([0,.15+k*.13,front+2-k*.55,12,.3,4-k*.8]);batch(root,rounded,concrete,entry);cube(root,glass,0,2.8,front+.4,8,5.3,.1);for(let s of[-1,1]){cube(root,chrome,s*1.6,2.8,front+.5,.08,5.3,.12);cube(root,chrome,s*.6,2.6,front+.6,.04,1,.06);}
 // Roof safety rail, cooling units with fan blades, water tank and service stairs.
 for(let side of[-1,1]){roofRail.push([0,b.h+1.2,side*(b.d/2-.7),b.w,.10,.1]);roofRail.push([side*(b.w/2-.7),b.h+1.2,0,.1,.10,b.d]);for(let x=-b.w/2+1;x<b.w/2;x+=4)roofRail.push([x,b.h+.65,side*(b.d/2-.7),.07,1.3,.07]);for(let z=-b.d/2+1;z<b.d/2;z+=4)roofRail.push([side*(b.w/2-.7),b.h+.65,z,.07,1.3,.07]);}batch(root,unitBox,steel,roofRail);
 const fans=[],blades=[];for(const a of b.roofLayout.cooling){let x=a[0]-b.x,z=a[2]-b.z;cube(root,steel,x,a[1],z,a[3],a[4],a[5],rounded);fans.push([x,b.h+3.44,z,1,1,1,Math.PI/2,0,0]);for(let j=0;j<6;j++)blades.push([x,b.h+3.46,z,2.7,.055,.3,0,j*Math.PI/3,0]);}batch(root,new T.TorusGeometry(1.65,.10,10,40),dark,fans);batch(root,unitBox,steel,blades);
 for(const a of b.roofLayout.steps)cube(root,steel,a[0]-b.x,a[1],a[2]-b.z,a[3],a[4],a[5]);const t=b.roofLayout.tank,tank=new T.Mesh(new T.CylinderGeometry(t.r,t.r,t.height,48,8),steel);tank.position.set(t.x-b.x,t.y,t.z-b.z);root.add(tank);
 for(let j=0;j<4;j++){const hoop=new T.Mesh(new T.TorusGeometry(2.66,.065,8,48),chrome);hoop.rotation.x=Math.PI/2;hoop.position.set(tank.position.x,b.h+1+j*1.1,tank.position.z);root.add(hoop);}
 return root;}
 function updateBuildings(quality){if(++detailTick%20!==1)return;const count=quality==='ultra'?28:quality==='high'?16:6,range=quality==='ultra'?900:quality==='high'?620:350;
 const near=buildings.map(b=>({b,d:Math.hypot(b.x-player.p.x,b.z-player.p.z)})).filter(o=>o.d<range).sort((a,b)=>a.d-b.d).slice(0,count),ids=new Set(near.map(o=>o.b.id));for(const [id,r]of buildingDetails){r.visible=ids.has(id);buildings[id].detailVisible=r.visible;}
 let made=0;for(const {b}of near){if(!buildingDetails.has(b.id)&&made<2){buildingDetails.set(b.id,makeBuilding(b));b.detailVisible=true;made++;}}
 if(buildingDetails.size>40){for(const [id,r]of buildingDetails){if(!ids.has(id)){detailRoot.remove(r);r.traverse(o=>{if(o.isInstancedMesh)o.dispose();if(o.geometry&&![unitBox,rounded,facadeBevel].includes(o.geometry)&&!Array.from(cache.values()).includes(o.geometry))o.geometry.dispose();});buildingDetails.delete(id);buildings[id].detailVisible=false;if(buildingDetails.size<=36)break;}}}}
 // Street furniture has thickness: lamps, benches, hydrants, planters.
 const posts=[],lampHeads=[],benchSlats=[],hydrants=[];for(let x=-11;x<=11;x++)for(let z=-11;z<=11;z++){for(let side of[-1,1]){posts.push([x*180+side*73,4.5,z*180+55,.13,9,.13]);posts.push([x*180+side*75,8.9,z*180+55,4,.12,.13]);lampHeads.push([x*180+side*77,8.75,z*180+55,1.2,.12,.55]);}for(let j=0;j<5;j++)benchSlats.push([x*180-69,.65,z*180-20+j*.17,3,.12,.12]);hydrants.push([x*180+71,.7,z*180-62,.3,1.4,.3]);}
 batch(scene,new T.CylinderGeometry(1,1,1,20,1),steel,posts.filter(p=>p[4]>1));batch(scene,rounded,steel,posts.filter(p=>p[4]<=1));batch(scene,rounded,warm,lampHeads);batch(scene,rounded,material('#635041'),benchSlats);batch(scene,new T.CylinderGeometry(1,1,1,24,4),material('#a33430'),hydrants);
 const nearbyTrees=new T.Group();scene.add(nearbyTrees);const treeBark=material('#665449'),leaf=material('#47664b');const treeSlots=[];
 for(let i=0;i<36;i++){const r=new T.Group();nearbyTrees.add(r);const branches=[];for(let j=0;j<5;j++){let a=j/5*Math.PI*2;const branch=new T.Mesh(new T.CylinderGeometry(.08,.18,3.6,14,4),treeBark);branch.position.set(Math.cos(a)*.65,5,Math.sin(a)*.65);branch.rotation.z=Math.cos(a)*.45;branch.rotation.x=Math.sin(a)*.45;r.add(branch);ell(r,leaf,Math.cos(a)*1.5,6.4+(j%2)*1.4,Math.sin(a)*1.5,1.7,2.2,1.7,sphere(28,20));}treeSlots.push(r);}
 function updateTrees(quality){const bx=Math.round(player.p.x/180),bz=Math.round(player.p.z/180);let i=0;for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)for(let j=0;j<3;j++){const r=treeSlots[i++];r.position.set((bx+dx)*180-70,0,(bz+dz)*180-48+j*45);r.visible=quality!=='balanced';}for(;i<treeSlots.length;i++)treeSlots[i].visible=false;}
 const heroTriangles=()=>{let count=0;hero.traverseVisible(o=>{if(o.isMesh&&o.visible)count+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;});return Math.round(count);};
 function update(time,quality){updatePeople(time,quality);updateBuildings(quality);updateTrees(quality);for(const p of vehicleParts){for(let i=0;i<cars.length;i++){const c=cars[i];tmp.position.set(c.x+p.offset[0],p.offset[1],c.z+p.offset[2]);tmp.scale.set(...p.scale);tmp.rotation.set(...p.rot);if(p.spin==='z')tmp.rotateZ(-time*c.speed/.43);if(p.spin==='y')tmp.rotateY(-time*c.speed/.43);tmp.updateMatrix();p.mesh.setMatrixAt(i,tmp.matrix);}p.mesh.instanceMatrix.needsUpdate=true;}}
 return{ready,update,createPassenger,posePerson,closePeople,bossRigs,heroTriangles:heroTriangles(),getInfo:()=>({heroTriangles:heroTriangles(),detailedBuildings:buildingDetails.size,detailedPedestrians:closePeople.filter(p=>p.root.visible).length})};
}
