import {installLiteDetail} from './detail-lite.mjs?v=angular-2';
import {installAngularHero,crowdShape} from './angular.mjs?v=angular-2';
import {BOSS_DEFS,assignBosses,resetBosses} from './bosses.mjs';
import {roofLayout,roofColliders,boxCollider,containsXZ,topAt,clearRoofPoint} from './rooftops.mjs';
import {EventDirector,npcPose,smooth} from './events.mjs';
import {createCharacter} from './character.js';
import {installDetail} from './detail.js';
import * as THREE from './vendor/three.module.js';
import {constrainRope,clamp,segmentBoxEntry,steerAir} from './physics.mjs?v=steering-1';
const $=id=>document.getElementById(id),V=THREE.Vector3,UP=new V(0,1,0),keys={},clock=new THREE.Clock();
const launchQuality=window.__spiderQuality||'high',fastest=launchQuality==='low',lowGraphics=fastest||launchQuality==='lowshape',angular=launchQuality==='lowshape';
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:!lowGraphics,powerPreference:'high-performance'});}catch(e){$('fatal').hidden=false;$('fatal').textContent='This game needs WebGL 2. Please enable hardware acceleration in your browser and reload.';throw e;}
renderer.setPixelRatio(lowGraphics?Math.min(.55,960/innerWidth,540/innerHeight):Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=false;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.outputColorSpace=THREE.SRGBColorSpace;$('game').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#b7bbc9');scene.fog=new THREE.FogExp2('#c3b7bd',.00031);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.15,6500);const hemi=new THREE.HemisphereLight(0xbddaff,0x60504a,2);scene.add(hemi);const heroLight=new THREE.DirectionalLight(0xcde4ff,1.0);scene.add(heroLight,heroLight.target);
const sun=new THREE.DirectionalLight(0xffd1a0,3.7);sun.position.set(-400,650,-500);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-130,right:130,top:130,bottom:-130,near:1,far:1400});sun.shadow.bias=-.0003;sun.shadow.normalBias=.4;scene.add(sun,sun.target);
const skyGeo=new THREE.SphereGeometry(5800,32,20),skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#527caa')},bottom:{value:new THREE.Color('#ead0b8')}},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 vP;uniform vec3 top;uniform vec3 bottom;void main(){float h=normalize(vP).y;gl_FragColor=vec4(mix(bottom,top,smoothstep(-.05,.85,h)),1.);}'});const sky=new THREE.Mesh(skyGeo,skyMat);scene.add(sky);
let seed=4471;function rand(){seed=(1664525*seed+1013904223)>>>0;return seed/4294967296}const choose=a=>a[Math.floor(rand()*a.length)];
const mat=(color,rough=.75,metal=0)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});
const boxGeo=new THREE.BoxGeometry(1,1,1),sphereGeo=new THREE.SphereGeometry(1,24,16),dummy=new THREE.Object3D();
function box(w,h,d,m,x=0,y=0,z=0,parent=scene){const o=new THREE.Mesh(boxGeo,m);o.scale.set(w,h,d);o.position.set(x,y,z);parent.add(o);return o;}
function ellipsoid(parent,m,x,y,z,sx,sy,sz,segments=32){if(lowGraphics)segments=12;const mesh=new THREE.Mesh(segments===24?sphereGeo:new THREE.SphereGeometry(1,segments,Math.round(segments*.7)),m);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);parent.add(mesh);return mesh;}
const WORLD=2250,STEP=180,buildings=[],blockMap=new Map(),city=new THREE.Group();scene.add(city);
function facade(style){const c=document.createElement('canvas');c.width=128;c.height=256;const g=c.getContext('2d');g.fillStyle=['#526678','#7e776f','#3c546b','#818690'][style];g.fillRect(0,0,128,256);for(let y=0;y<256;y+=16){for(let x=0;x<128;x+=16){g.fillStyle=rand()<.16?'#dfcb9b':choose(['#7894ac','#34495b','#5f7e96','#b0b5b1']);g.fillRect(x+2,y+2,11,11);g.fillStyle='#c4ccce44';g.fillRect(x+2,y+2,11,2);}g.fillStyle='#161c2430';g.fillRect(0,y+14,128,2);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;return t;}
const roofMat=mat('#4f5860'),buildingMats=[];for(let i=0;i<4;i++){const t=facade(i);buildingMats.push(new THREE.MeshStandardMaterial({map:t,color:0xffffff,roughness:i===2?.28:.66,metalness:i===2?.45:.1}));}
const roadMat=mat('#242e39'),walkMat=mat('#72808a'),markMat=mat('#b6b6a7'),grassMat=mat('#324e40'),trunkMat=mat('#635246'),leafMat=mat('#375c47');box(WORLD*2+400,2,WORLD*2+400,roadMat,0,-1,0);
const water=box(1400,1,6500,new THREE.MeshStandardMaterial({color:'#366b88',metalness:.6,roughness:.23}),WORLD+680,-3,0);
const roadLines=[],walks=[],trees=[],roofBits=[],ledges=[];
for(let ix=-12;ix<=12;ix++)for(let iz=-12;iz<=12;iz++){
 const x=ix*STEP,z=iz*STEP;walks.push([x,.1,z,146,.3,146]);
 const park=(ix===-3&&iz>=-2&&iz<=1)||(ix===4&&iz===3)||(ix===-6&&iz===-5);if(park){box(132,.4,132,grassMat,x,.2,z,city);for(let t=0;t<15;t++)trees.push([x+(rand()-.5)*115,z+(rand()-.5)*115,5+rand()*8]);continue;}
 let dist=Math.hypot(ix,iz),h=dist<5?130+rand()*340:35+rand()*190;if(ix===0&&iz===0)h=760;if(ix===2&&iz===-2)h=580;if(ix===-2&&iz===1)h=660;
 const w=85+rand()*45,d=80+rand()*50,style=Math.floor(rand()*4),b={x,z,w,d,h,id:buildings.length,style};buildings.push(b);blockMap.set(ix+','+iz,b);
 b.roofLayout=roofLayout(b);b.baseColliders=roofColliders(b.roofLayout,false);b.detailColliders=roofColliders(b.roofLayout,true);roofBits.push(...b.roofLayout.base);
 for(let s=0;s<4;s++)ledges.push([x,h*.33+s*h*.22,z,w+1,1.2,d+1]);


 for(let j=0;j<3;j++)trees.push([x-70,z-48+j*45,5+rand()*4]);
}
const staticBatches=[];function instances(geo,material,arr){const m=new THREE.InstancedMesh(geo,material,arr.length);for(let i=0;i<arr.length;i++){const a=arr[i];dummy.position.set(a[0],a[1],a[2]);dummy.rotation.set(0,0,0);dummy.scale.set(a[3],a[4],a[5]);dummy.updateMatrix();m.setMatrixAt(i,dummy.matrix)}m.receiveShadow=true;scene.add(m);if(lowGraphics){m.frustumCulled=false;staticBatches.push({mesh:m,items:arr});}return m;}
// Instance whole districts; facade UVs follow real building dimensions.
for(let style=0;style<4;style++){
 const material=buildingMats[style];
 material.onBeforeCompile=shader=>{
 shader.vertexShader='varying vec2 vFacadeUV;\n'+shader.vertexShader;
 shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>
 vec3 facadeP=(instanceMatrix*vec4(position,1.0)).xyz;
 vFacadeUV=vec2(abs(normal.x)>.5?facadeP.z:facadeP.x,facadeP.y)/vec2(32.0,64.0);`);
 shader.fragmentShader='varying vec2 vFacadeUV;\n'+shader.fragmentShader;
 shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',THREE.ShaderChunk.map_fragment.replace('vMapUv','vFacadeUV'));
 };
 instances(boxGeo,material,buildings.filter(b=>b.style===style).map(b=>[b.x,b.h/2,b.z,b.w,b.h,b.d]));
}
instances(boxGeo,walkMat,walks);instances(boxGeo,roofMat,roofBits);instances(boxGeo,mat('#87929b',.5,.3),ledges);
const trunks=[],crowns=[];for(const [x,z,h]of trees){trunks.push([x,h*.32,z,.6,h*.65,.6]);crowns.push([x,h*.75,z,h*.3,h*.4,h*.3]);}instances(boxGeo,trunkMat,trunks);instances(new THREE.IcosahedronGeometry(1,lowGraphics?0:2),leafMat,crowns);
for(let k=-12;k<=12;k++){for(let n=-2200;n<2200;n+=22){roadLines.push([k*180+90,.04,n,.25,.03,9]);roadLines.push([n,.04,k*180+90,9,.03,.25]);}}
instances(boxGeo,markMat,roadLines);
function updateNearbyCity(){if(!lowGraphics)return;for(const {mesh,items}of staticBatches){let count=0;for(const a of items){if(Math.hypot(a[0]-player.p.x,a[2]-player.p.z)>650+Math.max(a[3],a[5])*.5)continue;dummy.position.set(a[0],a[1],a[2]);dummy.rotation.set(0,0,0);dummy.scale.set(a[3],a[4],a[5]);dummy.updateMatrix();mesh.setMatrixAt(count++,dummy.matrix);}mesh.count=count;mesh.instanceMatrix.needsUpdate=true;}}
// Detailed suit with articulated limbs, raised seams and fabric normal detail.
const texC=document.createElement('canvas');texC.width=texC.height=128;const tc=texC.getContext('2d');tc.fillStyle='#8080ff';tc.fillRect(0,0,128,128);for(let i=0;i<128;i+=4){tc.strokeStyle=i%8?'#7189ed':'#8d75ff';tc.beginPath();tc.moveTo(i,0);tc.lineTo(i+128,128);tc.stroke();}const normal=new THREE.CanvasTexture(texC);normal.wrapS=normal.wrapT=THREE.RepeatWrapping;normal.repeat.set(5,5);
const red=new THREE.MeshStandardMaterial({color:'#b91332',roughness:.47,metalness:.15,normalMap:normal,normalScale:new THREE.Vector2(.25,.25)}),blue=new THREE.MeshStandardMaterial({color:'#123659',roughness:.48,metalness:.18,normalMap:normal}),black=mat('#111827',.4),white=mat('#edf8ff',.19,.45),webMat=new THREE.LineBasicMaterial({color:'#102134'});
const hero=new THREE.Group();scene.add(hero);const torso=ellipsoid(hero,red,0,1.4,0,.42,.59,.255,48);ellipsoid(hero,blue,0,1.03,0,.34,.27,.22,40);ellipsoid(hero,red,-.21,1.62,.11,.23,.24,.16,40);ellipsoid(hero,red,.21,1.62,.11,.23,.24,.16,40);ellipsoid(hero,red,0,1.99,0,.14,.2,.14,32);
const head=new THREE.Group();head.position.y=2.23;hero.add(head);ellipsoid(head,red,0,0,0,.245,.31,.237,56);
function curveLine(parent,points,material=webMat){const g=new THREE.BufferGeometry().setFromPoints(points);const l=new THREE.Line(g,material);parent.add(l);return l;}
for(let i=0;i<12;i++){const a=i/12*Math.PI*2;let pts=[];for(let j=1;j<24;j++){const p=j/24*Math.PI;pts.push(new V(Math.sin(p)*Math.cos(a)*.247,Math.cos(p)*.312,Math.sin(p)*Math.sin(a)*.24))}curveLine(head,pts);}
for(let j=1;j<8;j++){const p=j/8*Math.PI,pts=[];for(let i=0;i<=64;i++){let a=i/64*Math.PI*2;pts.push(new V(Math.sin(p)*Math.cos(a)*.249,Math.cos(p)*.312,Math.sin(p)*Math.sin(a)*.241))}curveLine(head,pts);}
function eye(side){const sh=new THREE.Shape();sh.moveTo(side*.025,.075);sh.quadraticCurveTo(side*.14,.14,side*.221,.145);sh.quadraticCurveTo(side*.20,-.055,side*.10,-.073);sh.quadraticCurveTo(side*.045,-.055,side*.025,.075);const outer=new THREE.Mesh(new THREE.ShapeGeometry(sh,24),black);outer.position.z=.216;head.add(outer);const inner=new THREE.Mesh(new THREE.ShapeGeometry(sh,24),white);inner.scale.set(.78,.77,1);inner.position.set(side*.023,.01,.224);head.add(inner);}eye(-1);eye(1);
for(let j=0;j<9;j++){const y=1.05+j*.1,r=Math.sqrt(Math.max(0,1-((y-1.4)/.6)**2)),pts=[];for(let k=0;k<=64;k++){let a=k/64*Math.PI*2;pts.push(new V(Math.cos(a)*.425*r,y,Math.sin(a)*.26*r))}curveLine(hero,pts);}
for(let i=0;i<12;i++){const a=i/12*Math.PI*2,pts=[];for(let j=0;j<25;j++){let p=.4+j/25*2.3;pts.push(new V(Math.sin(p)*Math.cos(a)*.426,1.4+Math.cos(p)*.595,Math.sin(p)*Math.sin(a)*.26))}curveLine(hero,pts);}
ellipsoid(hero,black,0,1.62,.272,.054,.11,.018);for(let s of [-1,1])for(let j=0;j<4;j++){const yy=1.65-j*.035;curveLine(hero,[new V(0,yy,.275),new V(s*.11,yy+.09-j*.045,.27),new V(s*.20,yy+.16-j*.09,.24)],new THREE.LineBasicMaterial({color:0x080d15}));}
ellipsoid(hero,black,0,1.52,-.263,.08,.16,.02,32);for(let side of [-1,1])for(let j=0;j<4;j++){const yy=1.6-j*.055;curveLine(hero,[new V(0,yy,-.28),new V(side*.18,yy+.12-j*.05,-.25),new V(side*.31,yy+.24-j*.12,-.18)],new THREE.LineBasicMaterial({color:0x080d15}));}
function limb(x,y,upperLen,lowerLen,arm){const pivot=new THREE.Group();pivot.position.set(x,y,0);hero.add(pivot);ellipsoid(pivot,arm?red:blue,0,-upperLen*.45,0,arm?.16:.21,upperLen*.6,arm?.15:.20,40);const joint=new THREE.Group();joint.position.y=-upperLen;pivot.add(joint);ellipsoid(joint,arm?red:blue,0,-lowerLen*.44,0,arm?.115:.145,lowerLen*.57,arm?.12:.15,36);if(arm){ellipsoid(joint,red,0,-lowerLen,.02,.095,.15,.07,32);for(let f=0;f<4;f++)ellipsoid(joint,red,(f-1.5)*.043,-lowerLen-.11,.04,.026,.08,.027,24);}else{ellipsoid(joint,red,0,-lowerLen+.10,.035,.15,.28,.16,40);ellipsoid(joint,red,0,-lowerLen-.08,.13,.15,.12,.25,36);}return{pivot,joint};}
const arms=[limb(-.46,1.82,.44,.43,true),limb(.46,1.82,.44,.43,true)],legs=[limb(-.20,.96,.48,.48,false),limb(.20,.96,.48,.48,false)];hero.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});
const angularHero=angular?installAngularHero({hero,head,arms,legs}):null;
const player={p:new V(90,145,80),v:new V(0,0,0),ground:false,hp:100,yaw:Math.PI,anchor:null,rope:0,attack:0,dodge:0,carrying:false};let mode='menu',paused=false,time=0,cameraYaw=Math.PI,cameraPitch=0,swingHeld=false,zipTime=0,zipTarget=null,toastTime=0,accum=0,selectedAnchor=null;
const ropeGeo=new THREE.BufferGeometry().setFromPoints([new V(),new V()]),ropeMesh=new THREE.Line(ropeGeo,new THREE.LineBasicMaterial({color:'#f0f6ff'}));scene.add(ropeMesh);ropeMesh.visible=false;
const director=new EventDirector();const effects=[];function beam(from,to,color=0xc6f4ff){const l=curveLine(scene,[from.clone(),to.clone()],new THREE.LineBasicMaterial({color,transparent:true,opacity:1}));effects.push({mesh:l,t:.3,max:.3});}
// Batched pedestrian bodies keep crowds affordable on laptop GPUs.
const npcCount=lowGraphics?64:330,npcs=[],npcParts=[];const npcMat=mat('#fff',.8);for(let k=0;k<6;k++){const geo=angular?crowdShape(k):k===0?new THREE.SphereGeometry(1,lowGraphics?8:16,lowGraphics?6:12):new THREE.CapsuleGeometry(1,1,lowGraphics?2:4,lowGraphics?4:8);const m=new THREE.InstancedMesh(geo,npcMat,npcCount);m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);m.frustumCulled=false;m.castShadow=true;scene.add(m);npcParts.push(m);}
function spawnNPC(n,near=false){const ix=Math.round((player.p.x+(rand()-.5)*(near?700:3300))/STEP),iz=Math.round((player.p.z+(rand()-.5)*(near?700:3300))/STEP),axis=rand()<.5;n.p.set(clamp(ix*STEP+(axis?72:(rand()-.5)*120),-2180,2180),.35,clamp(iz*STEP+(axis?(rand()-.5)*120:72),-2180,2180));n.dir=axis?0:Math.PI/2;n.roof=null;if(n.hostile){const nearby=buildings.slice().sort((a,b)=>(Math.hypot(a.x-player.p.x,a.z-player.p.z)+Math.abs(a.h-player.p.y)*.3)-(Math.hypot(b.x-player.p.x,b.z-player.p.z)+Math.abs(b.h-player.p.y)*.3)).slice(0,8);n.roof=choose(nearby);n.p.copy(clearRoofPoint(n.roof,.18+rand()*.19,rand()<.5?-1:1));}n.origin=n.p.clone();n.attackCooldown=0;n.down=0;n.hp=n.hostile?80:45;n.flee=0;n.web=0;n.mission=false;n.event=null;n.downAge=0;}
for(let i=0;i<npcCount;i++){const n={p:new V(),dir:0,hostile:i%7===0,hp:60,down:0,flee:0,web:0,mission:false,phase:rand()*10,hair:choose(['#292523','#715a42','#27232b','#a29583']),pants:'#27364a',color:choose(['#879997','#e6cabb','#b68a68','#704c3b']),shirt:choose(['#c5b7a3','#6f90b0','#243746','#52635a','#934c55','#d6d9da'])};spawnNPC(n,true);npcs.push(n);for(let k=0;k<6;k++)npcParts[k].setColorAt(i,new THREE.Color(k===0?n.color:k<2?(n.hostile?'#702936':n.shirt):'#27364a'));}
const carColors=['#c6cdd2','#d8b771','#902c37','#283d55','#586c70'];const cars=[],carCount=lowGraphics?20:100;const carBody=new THREE.InstancedMesh(boxGeo,mat('#fff',.35,.4),carCount),carTop=new THREE.InstancedMesh(boxGeo,mat('#34485d',.2,.5),carCount);scene.add(carBody,carTop);for(let i=0;i<carCount;i++){cars.push({x:(Math.floor(rand()*24)-12)*180+83,z:(rand()-.5)*4300,speed:8+rand()*10});carBody.setColorAt(i,new THREE.Color(choose(carColors)));}
const bosses=assignBosses(npcs,buildings);let defeatedBosses=[];try{const value=JSON.parse(localStorage.getItem('spider-bosses-v2')||'[]');if(Array.isArray(value))defeatedBosses=value.filter(id=>BOSS_DEFS.some(b=>b.id===id));}catch{}
const bossWarnings=new Map();for(const n of bosses){const mesh=new THREE.Mesh(new THREE.RingGeometry(.85,1,80),new THREE.MeshBasicMaterial({color:n.boss.trim,transparent:true,opacity:.55,side:THREE.DoubleSide,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.visible=false;scene.add(mesh);bossWarnings.set(n,mesh);}
function defeatBoss(n){if(n.dead)return;n.dead=true;n.down=Infinity;n.downAge=0;n.web=0;if(mode==='campaign'&&!defeatedBosses.includes(n.boss.id)){defeatedBosses.push(n.boss.id);try{localStorage.setItem('spider-bosses-v2',JSON.stringify(defeatedBosses));}catch{}}toast(n.boss.name+' defeated'+(mode==='campaign'?' · '+defeatedBosses.length+' / '+bosses.length:''),5);}
const missionMarker=new THREE.Group();scene.add(missionMarker);const ring=new THREE.Mesh(new THREE.TorusGeometry(4,.12,8,64),new THREE.MeshBasicMaterial({color:'#67dcff'}));ring.rotation.x=Math.PI/2;missionMarker.add(ring);const pillar=box(.2,70,.2,new THREE.MeshBasicMaterial({color:'#67dcff',transparent:true,opacity:.32}),0,35,0,missionMarker);missionMarker.visible=false;
const passenger=new THREE.Group();scene.add(passenger);ellipsoid(passenger,mat('#c5a186'),0,1.65,0,.2,.24,.2,24);ellipsoid(passenger,mat('#e5aa39'),0,1.13,0,.28,.4,.18,24);for(let side of [-1,1]){ellipsoid(passenger,mat('#31465d'),side*.15,.42,0,.12,.42,.13,24);ellipsoid(passenger,mat('#e5aa39'),side*.36,1.08,0,.09,.36,.1,24);}passenger.visible=false;
const rescued={p:new V(),dir:0,phase:0,rescueState:'waiting',safeAge:0};
const campaign=[
 ['01 / FRIENDLY NEIGHBORHOOD','A city in motion','reach',90,55,-270,'Reach the waterfront overlook. Hold Space to swing; release to launch.','Dispatch: Reports of stolen emergency equipment at the docks.'],
 ['01 / FRIENDLY NEIGHBORHOOD','After hours','fight',270,1,-270,'Stop the crew stealing emergency supplies.','Those crates belong to Aegis Response. Why steal your own equipment?'],
 ['01 / FRIENDLY NEIGHBORHOOD','Above the traffic','rescue',450,125,-90,'Reach the stranded worker and press C. Bring them to street level.','Worker: They cut the safety systems remotely. I saw the company logo.'],
 ['01 / FRIENDLY NEIGHBORHOOD','The first signal','hack',-90,155,-90,'Reach the rooftop relay. Hold C nearby to trace its signal.','Aegis is routing emergency calls through a private network.'],
 ['01 / FRIENDLY NEIGHBORHOOD','Running evidence','chase',-270,85,-450,'Stay close to the courier drone to intercept its data.','The drone carries a schedule of emergencies that have not happened yet.'],
 ['01 / FRIENDLY NEIGHBORHOOD','Loose ends','fight',-450,1,-270,'Protect the evidence from the recovery team.','Reporter Maya Chen agrees to investigate. Someone planned every incident.'],
 ['02 / FALSE SECURITY','Glass ceiling','reach',360,590,-360,'Climb to the upper relay on the glass tower.','Maya: Follow the money. Aegis is buying the blocks hit hardest.'],
 ['02 / FALSE SECURITY','Silent witness','hack',630,180,-450,'Hold C at the rooftop terminal to recover the ownership records.','The acquisitions lead to a hidden research site.'],
 ['02 / FALSE SECURITY','Collateral','rescue',810,110,-90,'Rescue the technician before another system fails.','Technician: Their drones share one override frequency.'],
 ['02 / FALSE SECURITY','The convoy','chase',810,80,270,'Intercept the moving relay drone. Keep within 55 meters.','The override key is split across neighborhood transmitters.'],
 ['02 / FALSE SECURITY','Unwelcome guests','fight',630,1,450,'Defeat the security squad guarding the transmitter.','Maya: The story is ready. I need the final proof.'],
 ['02 / FALSE SECURITY','Proof of intent','hack',270,170,630,'Download the emergency simulation logs.','These are not simulations. The next event is a citywide blackout.'],
 ['03 / BLACKOUT','Lights out','reach',-90,120,810,'Get above the darkened residential blocks.','Dispatch: Elevators trapped, streets blocked. We need help everywhere.'],
 ['03 / BLACKOUT','One at a time','rescue',-450,140,630,'Carry the trapped resident down to the street.','Resident: My neighbor is still up there. Please keep looking.'],
 ['03 / BLACKOUT','Emergency power','hack',-630,90,450,'Restore the local emergency grid. Hold C at the relay.','A neighborhood comes back online. The network notices you.'],
 ['03 / BLACKOUT','Under cover','fight',-810,1,90,'Clear the armed patrol from the evacuation route.','The evacuation can proceed. Aegis orders a lockdown.'],
 ['03 / BLACKOUT','Falling skies','chase',-810,140,-270,'Catch the damaged surveillance drone before its data is lost.','Its recordings reveal who authorized the blackout.'],
 ['03 / BLACKOUT','A higher calling','rescue',-360,675,180,'Reach the stranded engineer near the tower summit, then descend safely.','Engineer Vale: I built the core. I can help you shut it down.'],
 ['04 / HUNTED','No safe rooftops','fight',-450,1,-810,'Break through the response team.','Aegis labels you the cause of the crisis.'],
 ['04 / HUNTED','Dead channel','hack',-90,210,-990,'Disable the northern surveillance relay.','Vale: Four relay keys will open the central core.'],
 ['04 / HUNTED','Across the skyline','chase',450,180,-990,'Intercept the key carrier over the northern district.','First key secured. The network is adapting.'],
 ['04 / HUNTED','Human cost','rescue',990,160,-630,'Rescue the whistleblower from the isolated tower.','Whistleblower: They are moving everyone to the central district.'],
 ['04 / HUNTED','Breaking the perimeter','fight',1170,1,-90,'Defeat the perimeter guards.','Maya broadcasts the evidence. The city turns against Aegis.'],
 ['04 / HUNTED','Open circuit','hack',990,200,450,'Override the last outer relay.','Vale: The core is exposed. This is our chance.'],
 ['05 / CITY UNDER SIEGE','Gathering storm','reach',450,200,270,'Rendezvous above the central district.','Dispatch: We have your back. Finish this.'],
 ['05 / CITY UNDER SIEGE','Street by street','fight',270,1,90,'Clear the final security blockade.','The route to the tower is open.'],
 ['05 / CITY UNDER SIEGE','Last passenger','rescue',180,280,-180,'Bring the trapped researcher safely to the street.','Researcher: The core antenna is at the very top.'],
 ['05 / CITY UNDER SIEGE','Cut the feed','chase',90,260,-270,'Intercept the command drone circling the central tower.','Command link severed. Only the core remains.'],
 ['05 / CITY UNDER SIEGE','Above everything','hack',0,780,0,'Reach the tallest tower and hold C to shut down the core.','The network goes quiet. Across the city, the lights return.'],
 ['05 / CITY UNDER SIEGE','Your neighborhood','reach',90,110,270,'Return to the overlook. The city is yours again.','Maya: No company owns this city. It belongs to the people who show up for it.']
];
// Preserve the long story and weave a boss confrontation into every act.
for(let i=BOSS_DEFS.length-1;i>=0;i--){const def=BOSS_DEFS[i],after=[3,7,11,15,19,23,27,30][i];campaign.splice(after,0,['SUPER VILLAIN / '+(i+1)+' OF 8',def.name,'boss',def.xy[0],0,def.xy[1],def.hint,def.name+' is down. Follow the next lead.',def.id]);}
let saved=0;try{saved=clamp(Number(localStorage.getItem('spider-campaign-v2'))||0,0,campaign.length);}catch{}let missionIndex=saved,mission=null,missionTimer=0,missionTotal=0,missionKills=0,completeDelay=0;
const drone=new THREE.Group();const dm=mat('#354355',.3,.6);box(3,.8,2,dm,0,0,0,drone);for(let a of[-1,1])for(let b of[-1,1]){box(3,.15,.2,dm,a*1.5,0,b,drone);const rr=new THREE.Mesh(new THREE.TorusGeometry(.9,.09,6,20),mat('#131b29'));rr.rotation.x=Math.PI/2;rr.position.set(a*2,0,b*1.3);drone.add(rr);}scene.add(drone);const rotors=[];for(let a of[-1,1])for(let b of[-1,1])rotors.push(box(1.8,.04,.14,dm,a*2,.1,b*1.3,drone));drone.visible=false;
function toast(s,t=5){$('toast').textContent=s;toastTime=t;$('toast').style.opacity=1;}
function supportHeight(x,z,ceiling=Infinity){const b=blockMap.get(Math.round(x/STEP)+','+Math.round(z/STEP));return b?topAt(b,x,z,ceiling):0;}
function loadMission(){director.clear();player.carrying=false;rescued.event=null;rescued.rescueState='waiting';missionTimer=missionKills=0;for(const n of npcs)n.mission=false;if(missionIndex>=campaign.length&&defeatedBosses.length<bosses.length){missionIndex=campaign.findIndex(a=>a[2]==='boss'&&!defeatedBosses.includes(a[8]));}if(missionIndex>=campaign.length){mission=null;missionMarker.visible=drone.visible=false;$('objective').hidden=true;toast('CAMPAIGN COMPLETE · All eight supervillains defeated. The city is yours.',9);mode='free';$('modeLabel').textContent='FREE ROAM';return;}
const a=campaign[missionIndex];mission={chapter:a[0],title:a[1],type:a[2],p:new V(a[3],a[4],a[5]),text:a[6],outro:a[7],bossId:a[8]};if(mission.type==='boss'){const n=bosses.find(n=>n.boss.id===mission.bossId);n.mission=true;mission.p.copy(n.p);}if(['hack','rescue'].includes(mission.type)){const b=buildings.reduce((best,b)=>Math.hypot(b.x-mission.p.x,b.z-mission.p.z)<Math.hypot(best.x-mission.p.x,best.z-mission.p.z)?b:best,buildings[0]);mission.p.set(b.x+b.w*.35,b.h+1,b.z+b.d*.3);}else if(mission.type==='reach')mission.p.y=Math.max(mission.p.y,supportHeight(mission.p.x,mission.p.z)+3);if(mission.type==='chase'){for(let t=0;t<32;t++){const a=t/32*Math.PI*2;mission.p.y=Math.max(mission.p.y,supportHeight(mission.p.x+Math.cos(a)*100,mission.p.z+Math.sin(a)*100)+45);}}missionMarker.position.copy(mission.p);missionMarker.visible=true;drone.visible=mission.type==='chase';$('objective').hidden=false;$('chapter').textContent=mission.chapter;$('missionTitle').textContent=mission.title;$('missionText').textContent=mission.text;
if(mission.type==='fight'){missionTotal=4+Math.floor(missionIndex/6);for(let i=0;i<missionTotal;i++){let n=npcs[i];n.p.copy(mission.p).add(new V((i%3-1)*6,0,Math.floor(i/3)*6));n.p.y=.35;n.roof=null;n.origin=n.p.clone();n.hostile=true;n.hp=100+Math.floor(missionIndex/6)*15;n.down=n.web=0;n.mission=true;npcParts[1].setColorAt(i,new THREE.Color('#8c293e'));npcParts[1].instanceColor.needsUpdate=true;}}}
function finishMission(){if(completeDelay)return;toast(mission.outro,7);completeDelay=7;missionMarker.visible=false;drone.visible=false;player.hp=Math.min(100,player.hp+30);missionIndex++;try{localStorage.setItem('spider-campaign-v2',missionIndex);}catch{}}
function start(which){for(const k in keys)keys[k]=false;player.steer=0;cameraTurn=0;director.clear();player.event=null;player.carrying=false;player.hacking=false;player.defeatAge=null;player.jumpAge=player.landAge=player.hurtAge=99;mode=which;paused=false;$('menu').hidden=true;$('pause').hidden=true;$('hud').hidden=false;$('modeLabel').textContent=which==='free'?'FREE ROAM':'CAMPAIGN';player.hp=100;player.p.set(90,160,90);player.v.set(0,0,-15);player.anchor=null;cameraYaw=Math.PI;cameraPitch=0;swingHeld=false;completeDelay=0;mission=null;missionMarker.visible=drone.visible=passenger.visible=false;if(which==='campaign'&&saved>=campaign.length){defeatedBosses=[];try{localStorage.setItem('spider-bosses-v2','[]');}catch{}}resetBosses(bosses,which==='campaign'?defeatedBosses:[]);$('bossHud').hidden=true;if(which==='campaign'){missionIndex=saved>=campaign.length?0:saved;loadMission();}else{$('objective').hidden=true;toast('Free roam · No missions. Hold Space to swing. F attacks nearby people or enemies.',7);}initAudio();}
let mouseLocked=false,unlockEscapeUntil=0;
function releaseMouse(){if(document.pointerLockElement===renderer.domElement)document.exitPointerLock?.();}
function captureMouse(){if(mode==='menu'||paused||!renderer.domElement.requestPointerLock)return;try{const request=renderer.domElement.requestPointerLock();request?.catch(()=>toast('Click the game to try mouse look again. Arrow keys also work.',4));}catch{toast('Mouse capture unavailable. Use arrow keys to look.',4);}}
window.addEventListener('click',e=>{if(e.target===renderer.domElement)captureMouse();});
document.addEventListener('pointerlockchange',()=>{const wasLocked=mouseLocked;mouseLocked=document.pointerLockElement===renderer.domElement;if(wasLocked&&!mouseLocked){unlockEscapeUntil=Date.now()+300;if(mode!=='menu')togglePause(true);}});
window.addEventListener('mousemove',e=>{if(!mouseLocked||paused||mode==='menu')return;cameraYaw-=(e.movementX||0)*.0022;cameraPitch=clamp(cameraPitch+(e.movementY||0)*.0022,-.8,1.1);});
function togglePause(force){paused=force??!paused;$('pause').hidden=!paused;if(paused){releaseMouse();player.steer=0;cameraTurn=0;swingHeld=false;for(let k in keys)keys[k]=false;}}
$('freeBtn').onclick=()=>start('free');$('campaignBtn').onclick=()=>start('campaign');$('resumeBtn').onclick=()=>{if(mode==='menu')$('pause').hidden=true;else{togglePause(false);captureMouse();}};$('pauseButton').onclick=()=>togglePause();$('settingsBtn').onclick=()=>{$('pause').hidden=false;$('pauseTitle').textContent='Controls & settings';};$('menuBtn').onclick=()=>{mode='menu';releaseMouse();paused=false;passenger.visible=false;$('pause').hidden=true;$('menu').hidden=false;$('hud').hidden=true;saved=missionIndex;};$('restartBtn').onclick=()=>{if(mode==='campaign'){completeDelay=0;loadMission();player.hp=100;recover();}togglePause(false)};
$('continueLabel').textContent=saved&&saved<campaign.length?'Continue · '+defeatedBosses.length+' / 8 bosses defeated':'38 missions · Defeat all 8 supervillains';$('loading').textContent='Loading character…';$('freeBtn').disabled=$('campaignBtn').disabled=true;
function recover(){player.defeatAge=null;player.landAge=0;director.clear();player.event=null;player.carrying=false;const b=buildings.reduce((best,b)=>Math.hypot(b.x-player.p.x,b.z-player.p.z)<Math.hypot(best.x-player.p.x,best.z-player.p.z)?b:best,buildings[0]);const spot=clearRoofPoint(b);player.p.set(spot.x,spot.y+2,spot.z);player.v.set(0,0,0);player.anchor=null;player.hp=100;toast('Back on your feet.',2);}
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement||e.target instanceof HTMLInputElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(mode!=='menu'){if(mouseLocked||Date.now()<unlockEscapeUntil)togglePause(true);else togglePause();}return;}if(paused||mode==='menu'||player.defeatAge!=null)return;if(!keys[e.code]){if(e.code==='Space'){if($('toggleSwing').checked)swingHeld=!swingHeld;else swingHeld=true;if(player.ground){player.jumpAge=0;player.v.y=18;player.ground=false;}else attach();}if(e.code==='KeyF')attack(false);if(e.code==='KeyR')attack(true);if(e.code==='KeyQ'){player.dodge=.55;player.v.x+=Math.cos(cameraYaw)*17;player.v.z-=Math.sin(cameraYaw)*17;}if(e.code==='KeyE')zip();if(e.code==='KeyT')recover();}keys[e.code]=true;});
window.addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='Space'&&!$('toggleSwing').checked){swingHeld=false;player.anchor=null;}});window.addEventListener('blur',()=>{if(mode!=='menu'&&!paused)togglePause(true)});
function forward(){return new V(Math.sin(cameraYaw),0,Math.cos(cameraYaw));}
function ropeBlocked(a,end){for(const b of buildings){if(b.h<Math.min(a.y,end.y))continue;if(Math.max(a.x,end.x)<b.x-b.w/2||Math.min(a.x,end.x)>b.x+b.w/2||Math.max(a.z,end.z)<b.z-b.d/2||Math.min(a.z,end.z)>b.z+b.d/2)continue;const hit=segmentBoxEntry(a,end,{x:b.x-b.w/2+.1,y:0,z:b.z-b.d/2+.1},{x:b.x+b.w/2-.1,y:b.h,z:b.z+b.d/2-.1});if(hit!==null&&hit<.995)return true;}return false;}
function findAnchor(){const f=forward();let best=null,bestScore=-Infinity;for(const b of buildings){let dx=b.x-player.p.x,dz=b.z-player.p.z,hd=Math.hypot(dx,dz);if(hd>230||hd<15||b.h<player.p.y+12)continue;let dot=(dx*f.x+dz*f.z)/hd;if(dot<-.35)continue;let y=Math.min(b.h+1,player.p.y+65+hd*.35);let x=clamp(player.p.x+f.x*75,b.x-b.w/2,b.x+b.w/2),z=clamp(player.p.z+f.z*75,b.z-b.d/2,b.z+b.d/2);if(Math.abs(x-b.x)<b.w/2-.1&&Math.abs(z-b.z)<b.d/2-.1){if(Math.abs(dx)>Math.abs(dz))x=b.x-Math.sign(dx)*b.w/2;else z=b.z-Math.sign(dz)*b.d/2;}
let score=dot*100-Math.abs(hd-85)*.3-Math.abs(y-player.p.y-80)*.1;if(score>bestScore){const candidate=new V(x,y,z);if(!ropeBlocked(player.p,candidate)){bestScore=score;best=candidate;}}}
return best;}
function attach(){if(player.anchor||player.ground)return;const a=findAnchor();if(a){player.anchor=a;player.rope=player.p.distanceTo(a);if(Math.hypot(player.v.x,player.v.z)<10){const f=forward();player.v.addScaledVector(f,12);}constrainRope(player.p,player.v,player.anchor,player.rope);sfx(350,.08,.035);}}
function zip(){if(!selectedAnchor)return;const b=blockMap.get(Math.round(selectedAnchor.x/STEP)+','+Math.round(selectedAnchor.z/STEP));zipTarget=selectedAnchor.clone().add(new V(0,4,0));if(b)zipTarget.y=b.h+4;zipTime=Math.min(12,player.p.distanceTo(zipTarget)/65+1);player.anchor=null;beam(player.p.clone().add(new V(0,2,0)),zipTarget);sfx(650,.13,.03);}
function combatClear(a,b){const from=a.clone().add(new V(0,1.2,0)),to=b.clone().add(new V(0,1.2,0));for(const roof of buildings){if(Math.abs(roof.x-a.x)>roof.w/2+45||Math.abs(roof.z-a.z)>roof.d/2+45)continue;const solids=[boxCollider([roof.x,roof.h/2,roof.z,roof.w,roof.h,roof.d]),...(roof.detailVisible?roof.detailColliders:roof.baseColliders)];for(const c of solids){const t=segmentBoxEntry(from,to,{x:c.minX,y:c.bottom,z:c.minZ},{x:c.maxX,y:c.top,z:c.maxZ});if(t!==null&&t<1)return false;}}return true;}
function attack(web){if(player.defeatAge!=null||player.attack>0||player.carrying)return;if(player.event?.kind==='enemyPunch'&&player.event.target===player){const e=player.event;e.actor.attackCooldown=.8;director.release(e);}if(player.event)return;let target=null,best=Infinity,rank=Infinity;const f=forward();for(const n of npcs){if(n.down||n.event||n.dead)continue;const d=n.p.distanceTo(player.p),tow=n.p.clone().sub(player.p).normalize().dot(f);if(d>=(web?40:7)||(!web&&Math.abs(n.p.y-player.p.y)>1.5)||(d>3.5&&tow<=-.45)||!combatClear(player.p,n.p))continue;const score=d+(n.hostile?0:10);if(score<rank){rank=score;best=d;target=n;}}

 const kind=web?'web':!player.ground&&player.v.length()>10?'swingKick':'punch';const contact=web?.16+(target?best/95:0):.28,duration=Math.max(.72,contact+.35);player.attack=duration;
 const origin=player.p.clone(),impactSpeed=player.v.length();let hitDirection=f.clone();
 director.start(kind,player,target,{duration,contact,onStep(e,dt){if(!target)return;if(web&&e.t>.08&&!e.hit){const hand=character?character.bones.RightHand.getWorldPosition(new V()):angularHero?angularHero.handWorld(1):player.p.clone().add(new V(0,1.6,0));if(!e.line){e.line=curveLine(scene,[hand.clone(),hand.clone()],new THREE.LineBasicMaterial({color:0xe5f5ff,transparent:true,opacity:1}));effects.push({mesh:e.line,t:duration,max:duration});}const end=hand.clone().lerp(target.p.clone().add(new V(0,1.1,0)),smooth((e.t-.08)/(contact-.08)));const attr=e.line.geometry.attributes.position;attr.setXYZ(0,hand.x,hand.y,hand.z);attr.setXYZ(1,end.x,end.y,end.z);attr.needsUpdate=true;e.line.geometry.computeBoundingSphere();}const delta=target.p.clone().sub(player.p);delta.y=0;if(delta.lengthSq()>.001){hitDirection.copy(delta).normalize();player.yaw=Math.atan2(delta.x,delta.z);target.dir=Math.atan2(-delta.x,-delta.z);}if(!web&&!e.hit){const stop=target.p.clone().addScaledVector(hitDirection,-.92);stop.y=origin.y;player.p.lerpVectors(origin,stop,smooth(e.t/contact));player.v.x=player.v.z=0;}if(e.hit&&!web&&target.down<=0)target.p.addScaledVector(hitDirection,dt*2.2);},onContact(e){
 if(!target){sfx(180,.09,.03);return;}if(!web&&player.p.distanceTo(target.p)>3.2)return;
 if(web){target.web=target.boss?2:7;target.hp-=20;const wrist=character?character.bones.RightHand.getWorldPosition(new V()):angularHero?angularHero.handWorld(1):player.p.clone().add(new V(0,1.6,0));beam(wrist,target.p.clone().add(new V(0,1.1,0)));}else{target.hp-=40+Math.min(impactSpeed*.6,35);sfx(75,.13,.09);}target.flee=target.boss?0:8;if(target.hp<=0){if(target.boss)defeatBoss(target);else{target.down=25;target.downAge=0;if(target.mission)missionKills++;}}for(const n of npcs)if(!n.hostile&&n.p.distanceTo(target.p)<22)n.flee=9;
 }});
}
function enemyAttack(n){if(n.boss)return bossAttack(n);if(n.event||player.event||n.web||n.down||n.dead||n.attackCooldown>0)return;n.attackCooldown=1.65;const event=director.start('enemyPunch',n,player,{duration:1.0,contact:.4,onStep(e,dt){const d=player.p.clone().sub(n.p);d.y=0;n.dir=Math.atan2(d.x,d.z);if(!e.hit&&d.length()>.95)n.p.addScaledVector(d.normalize(),Math.min(n.p.distanceTo(player.p)-.95,dt*5));},onContact(){if(player.dodge<=0&&n.p.distanceTo(player.p)<1.4){player.hp-=8;player.hurtAge=0;sfx(90,.1,.04);}}});return event;}
function bossAttack(n){if(n.dead||n.event||player.event||n.web>0||n.attackCooldown>0||!combatClear(n.p,player.p))return;const def=n.boss,enraged=n.hp<n.maxHp*.5,windup=def.windup*(enraged?.8:1),duration=windup+1.4;n.attackCooldown=duration+.9;n.attackTarget=player.p.clone();const origin=n.p.clone(),target=n.attackTarget.clone(),direction=target.clone().sub(origin).setY(0).normalize();n.dir=Math.atan2(direction.x,direction.z);return director.start('enemyPunch',n,player,{duration,contact:windup,onStep(e){if(['charge','dive'].includes(def.style)&&!e.hit){const u=smooth((e.t/windup-.45)/.55),end=target.clone().addScaledVector(direction,-1.1);end.y=origin.y;n.p.lerpVectors(origin,end,u);n.p.x=clamp(n.p.x,n.roof.x-n.roof.w/2+3,n.roof.x+n.roof.w/2-3);n.p.z=clamp(n.p.z,n.roof.z-n.roof.d/2+3,n.roof.z+n.roof.d/2-3);}},onContact(){const warning=bossWarnings.get(n);warning.visible=false;const center=['charge','dive'].includes(def.style)?n.p:target;if(Math.abs(player.p.y-center.y)<3&&Math.hypot(player.p.x-center.x,player.p.z-center.z)<def.radius&&player.dodge<=0){player.hp-=def.damage*(enraged?1.2:1);player.hurtAge=0;sfx(55,.25,.08);}beam(n.p.clone().add(new V(0,1.4,0)),target.clone().add(new V(0,.15,0)));},onFinish(){n.attackTarget=null;}});}
function updateBossHUD(){let nearest=null,best=70;for(const n of bosses){const d=n.p.distanceTo(player.p);if(!n.dead&&d<best){nearest=n;best=d;}const warning=bossWarnings.get(n),e=n.event;warning.visible=!!(e&&e.actor===n&&!e.hit&&!n.dead&&n.attackTarget);if(warning.visible){warning.position.copy(n.attackTarget);warning.position.y+=.08;warning.scale.setScalar(n.boss.radius);warning.material.opacity=.25+.4*Math.sin(e.t/e.contact*Math.PI*.5);}}$('bossHud').hidden=!nearest;if(nearest){$('bossName').textContent=nearest.boss.name.toUpperCase();$('bossHealth').style.width=Math.max(0,nearest.hp/nearest.maxHp*100)+'%';$('bossStatus').textContent=nearest.event?.actor===nearest&&!nearest.event.hit?nearest.boss.attack+' · DODGE [Q]':nearest.web>0?'Webbed · attack [F]':nearest.attackCooldown>1?'Recovering · attack [F]':nearest.hp<nearest.maxHp*.5?'PHASE 2 · '+nearest.boss.hint:nearest.boss.hint;}}
let audioCtx,windGain;function initAudio(){try{audioCtx??=new AudioContext();audioCtx.resume();if(!windGain){const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.2;const source=audioCtx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=500;windGain=audioCtx.createGain();windGain.gain.value=0;source.connect(filter).connect(windGain).connect(audioCtx.destination);source.start();}}catch{}}
function sfx(freq,dur,gain){if(!audioCtx||!$('sound').checked)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.3,audioCtx.currentTime+dur);g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}
function collision(old,dt){const wasGround=player.ground;player.ground=false;const ix=Math.round(player.p.x/STEP),iz=Math.round(player.p.z/STEP),solids=[];
 for(let x=ix-1;x<=ix+1;x++)for(let z=iz-1;z<=iz+1;z++){const b=blockMap.get(x+','+z);if(!b)continue;solids.push(boxCollider([b.x,b.h/2,b.z,b.w,b.h,b.d],'building'),...(b.detailVisible?b.detailColliders:b.baseColliders));}
 // Use exact visible footprints for landing, and the character radius only for walls.
 let floor=.35;for(const c of solids){if(containsXZ(c,player.p.x,player.p.z)&&old.y>=c.top-.06&&player.p.y<=c.top+.0001&&player.v.y<=0)floor=Math.max(floor,c.top);}
 if(player.p.y<=floor+.0001&&player.v.y<=0){player.p.y=floor;player.v.y=0;player.ground=true;player.anchor=null;}
 for(const c of solids){if(player.p.y>=c.top-.0001||player.p.y+2.3<=c.bottom||!containsXZ(c,player.p.x,player.p.z,.36))continue;
 if(wasGround&&c.top-player.p.y<=.36&&containsXZ(c,player.p.x,player.p.z)){player.p.y=c.top;player.v.y=0;player.ground=true;continue;}
 if(c.kind==='cylinder'){const dx=player.p.x-c.x,dz=player.p.z-c.z,r=Math.hypot(dx,dz)||1;player.p.x=c.x+dx/r*(c.r+.36);player.p.z=c.z+dz/r*(c.r+.36);player.v.x=player.v.z=0;}else{const choices=[{d:Math.abs(player.p.x-(c.minX-.36)),axis:'x',v:c.minX-.36},{d:Math.abs(c.maxX+.36-player.p.x),axis:'x',v:c.maxX+.36},{d:Math.abs(player.p.z-(c.minZ-.36)),axis:'z',v:c.minZ-.36},{d:Math.abs(c.maxZ+.36-player.p.z),axis:'z',v:c.maxZ+.36}].sort((a,b)=>a.d-b.d);const hit=choices[0];player.p[hit.axis]=hit.v;player.v[hit.axis]=0;}
 if(keys.KeyW&&!player.event){player.climbing=true;player.v.y=keys.ShiftLeft||keys.ShiftRight?19:8;player.anchor=null;}else player.v.y=Math.max(player.v.y,-16);
 }
 player.p.x=clamp(player.p.x,-2240,2240);player.p.z=clamp(player.p.z,-2240,2240);
}
function physics(dt){director.tick(dt);const p=player,old=p.p.clone(),wasGround=p.ground;p.climbing=false;for(const key of ['jumpAge','landAge','hurtAge'])p[key]=(p[key]??99)+dt;p.attack=Math.max(0,p.attack-dt);p.dodge=Math.max(0,p.dodge-dt);const movementLocked=p.defeatAge!=null||p.event?.actor===p&&['punch','pickup','setdown'].includes(p.event.kind);const turnAxis=Number(!!keys.KeyD)-Number(!!keys.KeyA);if(!p.ground&&!movementLocked&&zipTime<=0)steerAir(p,turnAxis,dt);else p.steer=0;let f=forward();const airTurning=!p.ground&&Math.hypot(p.v.x,p.v.z)>1&&(turnAxis||Math.abs(p.steer)>.001);if(airTurning)f.set(p.v.x,0,p.v.z).normalize();let right=new V(-f.z,0,f.x),input=new V();if(keys.KeyW)input.add(f);if(keys.KeyS)input.sub(f);if(!airTurning){if(keys.KeyD)input.add(right);if(keys.KeyA)input.sub(right);}if(input.lengthSq()>0)input.normalize();const shift=keys.ShiftLeft||keys.ShiftRight;p.diving=!!shift&&!p.ground;p.zipping=zipTime>0;if(movementLocked)input.set(0,0,0);
if(p.ground){const target=input.multiplyScalar(shift?17:8);p.v.x=THREE.MathUtils.damp(p.v.x,target.x,10,dt);p.v.z=THREE.MathUtils.damp(p.v.z,target.z,10,dt);if(swingHeld){p.jumpAge=0;p.v.y=18;p.ground=false;}}else{p.v.y-=(shift?40:22)*dt;p.v.addScaledVector(input,(p.anchor?20:11)*dt);if(keys.KeyS&&p.anchor)p.v.multiplyScalar(Math.exp(-dt*.5));p.v.multiplyScalar(Math.exp(-dt*.035));if(swingHeld&&!p.anchor)attach();}
if(!swingHeld)p.anchor=null;else if(p.anchor&&ropeBlocked(p.p,p.anchor)){p.anchor=null;swingHeld=false;toast('Web obstructed · release Space and attach again',2);}if(zipTime>0&&zipTarget){zipTime-=dt;let d=zipTarget.clone().sub(p.p);if(d.length()<4){zipTime=0;p.v.multiplyScalar(.35);}else p.v.lerp(d.normalize().multiplyScalar(72),1-Math.exp(-dt*8));}
if(p.v.length()>110)p.v.setLength(110);p.p.addScaledVector(p.v,dt);if(p.anchor)constrainRope(p.p,p.v,p.anchor,p.rope);const impactVelocity=p.v.y;collision(old,dt);if(!wasGround&&p.ground&&impactVelocity<-3)p.landAge=0;if(p.anchor&&Math.abs(p.p.distanceTo(p.anchor)-p.rope)>.03){p.anchor=null;swingHeld=false;}
if(input.lengthSq()>.01&&p.ground)p.yaw=Math.atan2(input.x,input.z);else if(p.v.x*p.v.x+p.v.z*p.v.z>10)p.yaw=Math.atan2(p.v.x,p.v.z);
if(p.hp<=0){if(p.defeatAge==null){p.defeatAge=0;director.clear();p.anchor=null;swingHeld=false;p.v.set(0,0,0);}p.defeatAge+=dt;if(p.defeatAge>1.8){recover();if(mode==='campaign')loadMission();}}else p.hp=Math.min(100,p.hp+dt*.5);}
function updateNPCs(dt){let limit=lowGraphics?64:$('quality').value==='ultra'?330:$('quality').value==='high'?260:190;const q=new THREE.Quaternion(),ax=new V(1,0,0);for(let i=0;i<npcs.length;i++){const n=npcs[i];let dist=n.p.distanceTo(player.p);if(!n.boss&&!n.mission&&dist>850&&i<limit){spawnNPC(n,true);dist=n.p.distanceTo(player.p);}n.attackCooldown=Math.max(0,(n.attackCooldown||0)-dt);if(n.down>0){n.down=Math.max(0,n.down-dt);n.downAge=(n.downAge||0)+dt;}if(n.web>0)n.web-=dt;if(n.flee>0)n.flee-=dt;if(!n.boss&&!n.down&&n.hp<=0)n.hp=n.hostile?80:45;
let moving=0;if(!n.down&&!n.dead&&n.web<=0&&!n.event){if(n.boss&&dist<n.boss.range&&Math.abs(player.p.y-n.p.y)<3){if(n.attackCooldown<=0)bossAttack(n);}else if(n.hostile&&dist<22&&Math.abs(player.p.y-n.p.y)<5){const d=player.p.clone().sub(n.p);d.y=0;if(dist>2){d.normalize();n.p.addScaledVector(d,dt*4);n.dir=Math.atan2(d.x,d.z);moving=1;}else{enemyAttack(n);}}else if(n.flee>0){const d=n.p.clone().sub(player.p);d.y=0;d.normalize();n.p.addScaledVector(d,dt*6);n.dir=Math.atan2(d.x,d.z);moving=1;}else if(!n.mission){n.p.x+=Math.sin(n.dir)*dt*1.2;n.p.z+=Math.cos(n.dir)*dt*1.2;moving=.4;if(n.p.distanceTo(n.origin)>60)n.dir+=Math.PI;}}
if(n.roof){const b=n.roof;n.p.x=clamp(n.p.x,b.x-b.w/2+3,b.x+b.w/2-3);n.p.z=clamp(n.p.z,b.z-b.d/2+3,b.z+b.d/2-3);n.p.y=b.roofLayout.deck;for(const c of(b.detailVisible?b.detailColliders:b.baseColliders)){if(c.kind==='deck'||c.top<=n.p.y+.1||!containsXZ(c,n.p.x,n.p.z,.45))continue;const choices=[[Math.abs(n.p.x-c.minX+.5),'x',c.minX-.5],[Math.abs(c.maxX+.5-n.p.x),'x',c.maxX+.5],[Math.abs(n.p.z-c.minZ+.5),'z',c.minZ-.5],[Math.abs(c.maxZ+.5-n.p.z),'z',c.maxZ+.5]].sort((a,b)=>a[0]-b[0]);n.p[choices[0][1]]=choices[0][2];n.dir+=Math.PI*.5;}}
else{const b=blockMap.get(Math.round(n.p.x/STEP)+','+Math.round(n.p.z/STEP));if(b&&n.p.y<b.roofLayout.deck&&Math.abs(n.p.x-b.x)<b.w/2+1&&Math.abs(n.p.z-b.z)<b.d/2+1){n.p.x=b.x+Math.sign(n.p.x-b.x||1)*(b.w/2+2);n.dir+=Math.PI;}}
const pose=npcPose(n,time);const visible=(i<limit&&dist<500||n.mission||n.boss&&dist<550)&&!n.detailed;const walk=Math.sin(time*8+n.phase)*.45*moving;const specs=[[0,1.69,0,.21,.25,.21],[0,1.13,0,.30,.37,.19],[-.38,1.13,0,.10,.30,.10],[.38,1.13,0,.10,.30,.10],[-.16,.43,0,.12,.31,.12],[.16,.43,0,.12,.31,.12]];
for(let k=0;k<6;k++)npcParts[k].setColorAt(i,new THREE.Color(k===0?n.color:k<4?(n.boss?.color||(n.hostile?'#702936':n.shirt)):(n.boss?.color||n.pants)));for(let k=0;k<6;k++){const a=specs[k];dummy.position.set(a[0],a[1],a[2]);dummy.position.applyAxisAngle(new V(1,0,0),pose.lean);dummy.position.applyAxisAngle(UP,n.dir);dummy.position.y+=pose.bob;dummy.position.add(n.p);const swing=k===2?pose.arms[0]:k===3?pose.arms[1]:k===4?pose.legs[0]:k===5?pose.legs[1]:0;dummy.rotation.set(pose.lean+swing,n.dir,pose.roll);dummy.scale.set(a[3],a[4],a[5]);if(!visible)dummy.scale.setScalar(0);dummy.updateMatrix();npcParts[k].setMatrixAt(i,dummy.matrix);}}
for(const m of npcParts){m.instanceMatrix.needsUpdate=true;m.instanceColor.needsUpdate=true;}npcParts[1].instanceColor.needsUpdate=true;}
// Animation output must not become the next frame's yaw/pitch input: Euler
// decomposition changes branches past 90 degrees and produces rapid flipping.
let angularYaw=0,angularPitch=0,angularRoll=0,angularWalkPhase=0;
function animateHero(dt){angularHero?.beforePose();hero.position.copy(player.p);
const previousYaw=angularHero?angularYaw:hero.rotation.y,diff=Math.atan2(Math.sin(player.yaw-previousYaw),Math.cos(player.yaw-previousYaw));
const yaw=previousYaw+diff*(1-Math.exp(-dt*12)),speed=Math.hypot(player.v.x,player.v.z),swinging=!!player.anchor;
if(angularHero)angularWalkPhase+=dt*(keys.ShiftLeft?14:10);
const walk=Math.sin(angularHero?angularWalkPhase:time*(keys.ShiftLeft?14:10));
const pitch=THREE.MathUtils.damp(angularHero?angularPitch:hero.rotation.x,player.ground?0:clamp(-player.v.y*.009,-.65,.65),6,dt);
if(angularHero){angularYaw=yaw;angularPitch=pitch;angularRoll=player.dodge>0?Math.sin(player.dodge/.55*Math.PI)*.9:THREE.MathUtils.damp(angularRoll,0,12,dt);hero.rotation.set(angularPitch,angularYaw,angularRoll,'YXZ');}
else{hero.rotation.y=yaw;hero.rotation.x=pitch;}

for(let i=0;i<2;i++){if(angularHero){arms[i].pivot.rotation.y=0;arms[i].joint.rotation.y=arms[i].joint.rotation.z=0;legs[i].pivot.rotation.y=legs[i].pivot.rotation.z=0;legs[i].joint.rotation.y=legs[i].joint.rotation.z=0;}const side=i===0?-1:1;arms[i].pivot.rotation.z=THREE.MathUtils.damp(arms[i].pivot.rotation.z,swinging?side*2.65:player.ground?side*.08:side*.85,10,dt);arms[i].pivot.rotation.x=player.attack>0?(i===1?-1.8:0):player.ground?walk*side*Math.min(speed/15,.7):swinging?-.2:-.35;arms[i].joint.rotation.x=swinging?-.1:player.attack>0?-.6:-.2;legs[i].pivot.rotation.x=player.ground?walk*-side*Math.min(speed/14,.8):.25+side*.3;legs[i].joint.rotation.x=player.ground?Math.max(0,walk*side)*.7:.65+side*.3;}
if(!angularHero){if(player.dodge>0)hero.rotation.z=Math.sin(player.dodge/.55*Math.PI)*.9;else hero.rotation.z=THREE.MathUtils.damp(hero.rotation.z,0,12,dt);}
if(swinging){const up=player.anchor.clone().sub(player.p).normalize(),facing=new V(Math.sin(player.yaw),0,Math.cos(player.yaw));facing.addScaledVector(up,-facing.dot(up));if(facing.lengthSq()<.001)facing.set(0,0,1).addScaledVector(up,-up.z);facing.normalize();const right=new V().crossVectors(up,facing).normalize();facing.crossVectors(right,up).normalize();hero.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(right,up,facing));}
if(angularHero&&!swinging)angularHero.poseEvents(player,time);
if(swinging&&angularHero){angularHero.poseSwing();hero.updateMatrixWorld(true);}
ropeMesh.visible=swinging;if(swinging){const a=ropeGeo.attributes.position;const grip=angularHero?angularHero.gripWorld():new V(player.p.x,player.p.y+2.1,player.p.z);a.setXYZ(0,grip.x,grip.y,grip.z);a.setXYZ(1,player.anchor.x,player.anchor.y,player.anchor.z);a.needsUpdate=true;ropeGeo.computeBoundingSphere();}}
function updateMission(dt){player.hacking=false;if(mode!=='campaign'||!mission)return;if(completeDelay>0){completeDelay-=dt;if(completeDelay<=0)loadMission();return;}const d=player.p.distanceTo(mission.p);missionMarker.position.copy(mission.p);ring.rotation.z+=dt;ring.scale.setScalar(1+Math.sin(time*2)*.08);let txt=Math.round(d)+' m away';
if(mission.type==='boss'){const n=bosses.find(n=>n.boss.id===mission.bossId);mission.p.copy(n.p);txt=defeatedBosses.length+' / 8 supervillains defeated · '+Math.round(d)+' m';if(n.dead)finishMission();}
if(mission.type==='reach'){if(d<18)finishMission();}
if(mission.type==='fight'){txt=missionKills+' / '+missionTotal+' opponents stopped';if(missionKills>=missionTotal)finishMission();}
if(mission.type==='hack'){if(d<15&&keys.KeyC){missionTimer+=dt;player.hacking=true;}txt=d<15?'Hold C · '+Math.floor(missionTimer/8*100)+'%':txt;if(missionTimer>=8)finishMission();}
if(mission.type==='rescue'){
 if(!player.carrying&&!player.event&&rescued.rescueState==='waiting'&&d<4&&keys.KeyC){
  rescued.p.copy(mission.p);rescued.dir=player.yaw;const origin=player.p.clone(),start=rescued.p.clone(),facing=Math.atan2(start.x-origin.x,start.z-origin.z);
  director.start('pickup',player,rescued,{duration:1.15,contact:.68,onStep(e){player.v.set(0,0,0);player.yaw=facing;rescued.dir=facing;const off=new V(-Math.sin(player.yaw)*.5,.48,-Math.cos(player.yaw)*.5);rescued.p.lerpVectors(start,player.p.clone().add(off),smooth(e.t/e.duration));},onContact(){player.carrying=true;player.carryTarget=rescued;rescued.rescueState='carried';},onFinish(){toast('Passenger secured. Descend to any street and press C.',5);}});
 }
 if(player.carrying){txt='Passenger secured · descend to street level';if(player.p.y<4&&player.ground&&keys.KeyC&&!player.event){const start=rescued.p.clone(),end=player.p.clone().add(new V(Math.sin(player.yaw)*1.25,0,Math.cos(player.yaw)*1.25));end.y=.35;
  director.start('setdown',player,rescued,{duration:1.25,contact:.85,onStep(e){player.v.set(0,0,0);rescued.p.lerpVectors(start,end,smooth(e.t/e.duration));},onContact(){player.carrying=false;player.carryTarget=null;rescued.rescueState='safe';rescued.safeAge=0;},onFinish(){finishMission();}});
 }}else if(d<16)txt=d<4?'Hold C to lift passenger':'Move within 4 m of the passenger';
}
if(mission.type==='chase'){drone.position.set(mission.p.x+Math.cos(time*.13)*100,mission.p.y+Math.sin(time*.25)*20,mission.p.z+Math.sin(time*.13)*100);drone.rotation.y=-time*.13;drone.rotation.z=Math.sin(time*.6)*.07;for(const r of rotors)r.rotation.y=time*35;missionMarker.position.copy(drone.position);let dd=player.p.distanceTo(drone.position);if(dd<55)missionTimer+=dt;txt='Intercept · '+Math.floor(missionTimer/12*100)+'% · '+Math.round(dd)+' m';if(missionTimer>=12)finishMission();}
$('missionProgress').textContent=txt;}
const mapctx=$('map').getContext('2d');function minimap(){const c=mapctx;c.clearRect(0,0,200,200);c.fillStyle='#0c1b2b';c.fillRect(0,0,200,200);const scale=.14;c.save();c.translate(100,100);for(let b of buildings){let x=(b.x-player.p.x)*scale,z=(b.z-player.p.z)*scale;if(Math.abs(x)<120&&Math.abs(z)<120){c.fillStyle=b.h>400?'#52647a':'#293d50';c.fillRect(x-b.w*scale/2,z-b.d*scale/2,b.w*scale,b.d*scale);}}for(let n of npcs){if(n.down)continue;let x=(n.p.x-player.p.x)*scale,z=(n.p.z-player.p.z)*scale;if(Math.hypot(x,z)<96){c.fillStyle=n.boss?'#f4c968':n.hostile?'#ec5368':'#8ea6b7';c.fillRect(x-1,z-1,n.boss?6:n.hostile?3:1.5,n.boss?6:n.hostile?3:1.5);}}if(mode==='campaign'&&mission&&!completeDelay){let x=(missionMarker.position.x-player.p.x)*scale,z=(missionMarker.position.z-player.p.z)*scale,d=Math.hypot(x,z);if(d>87){x*=87/d;z*=87/d;}c.strokeStyle='#67dfff';c.lineWidth=2;c.beginPath();c.arc(x,z,5,0,7);c.stroke();}c.rotate(-player.yaw);c.fillStyle='#ff4b65';c.beginPath();c.moveTo(0,8);c.lineTo(-5,-5);c.lineTo(5,-5);c.closePath();c.fill();c.restore();}
let cameraTurn=0;
function updateCamera(dt){const lookAxis=Number(!!keys.ArrowLeft)-Number(!!keys.ArrowRight);cameraTurn=THREE.MathUtils.damp(cameraTurn,lookAxis*1.5,lookAxis?9:16,dt);cameraYaw+=cameraTurn*dt;if(!mouseLocked&&!keys.ArrowLeft&&!keys.ArrowRight&&Math.abs(cameraTurn)<.02&&Math.hypot(player.v.x,player.v.z)>4){let d=Math.atan2(Math.sin(player.yaw-cameraYaw),Math.cos(player.yaw-cameraYaw));cameraYaw+=d*(1-Math.exp(-dt*.55));}const sp=player.v.length(),f=forward();let target=player.p.clone().add(new V(0,2.4,0)).addScaledVector(f,5);const distance=10+sp*.08;const desired=player.p.clone().addScaledVector(f,-distance*Math.cos(cameraPitch));desired.y+=5+sp*.025+distance*Math.sin(cameraPitch)+(keys.ArrowUp?8:0)-(keys.ArrowDown?3:0);target.y+=Math.sin(cameraPitch)*-3;const b=blockMap.get(Math.round(desired.x/STEP)+','+Math.round(desired.z/STEP));if(b&&Math.abs(desired.x-b.x)<b.w/2+1&&Math.abs(desired.z-b.z)<b.d/2+1&&desired.y<b.h)desired.lerp(player.p.clone().add(new V(0,3,0)),.85);camera.position.lerp(desired,1-Math.exp(-dt*6));camera.lookAt(target);camera.fov=THREE.MathUtils.damp(camera.fov,65+Math.min(sp*.15,13),3,dt);camera.updateProjectionMatrix();}
function lighting(){const v=$('timeOfDay').value;if(v==='night'){scene.fog.color.set('#152438');skyMat.uniforms.top.value.set('#020816');skyMat.uniforms.bottom.value.set('#31425d');sun.color.set('#a8c7ff');sun.intensity=.7;hemi.intensity=.8;renderer.toneMappingExposure=1.2;}else if(v==='day'){scene.fog.color.set('#adcadd');skyMat.uniforms.top.value.set('#467faf');skyMat.uniforms.bottom.value.set('#c9dfeb');sun.color.set('#fff1da');sun.intensity=3.5;hemi.intensity=2;renderer.toneMappingExposure=1;}else{scene.fog.color.set('#c3b7bd');skyMat.uniforms.top.value.set('#527caa');skyMat.uniforms.bottom.value.set('#ead0b8');sun.color.set('#ffd1a0');sun.intensity=3.7;hemi.intensity=2;renderer.toneMappingExposure=1.1;}}$('timeOfDay').onchange=lighting;$('quality').onchange=()=>{const q=$('quality').value;try{localStorage.setItem('spider-graphics',q);}catch{}if((['low','lowshape'].includes(q))!==lowGraphics||(q==='low')!==fastest){location.reload();return;}renderer.setPixelRatio(lowGraphics?Math.min(.55,960/innerWidth,540/innerHeight):Math.min(devicePixelRatio,q==='ultra'?2:q==='high'?1.65:1.0));renderer.shadowMap.enabled=q==='high'||q==='ultra';camera.far=lowGraphics?1000:6500;camera.updateProjectionMatrix();scene.fog.density=lowGraphics?.002:.00031;};
const detail=(lowGraphics?installLiteDetail:installDetail)({scene,hero,head,arms,legs,red,blue,black,buildings,npcs,cars,carBody,carTop,player,renderer,fastest:lowGraphics,angular});
const passengerRig=detail.createPassenger(passenger);
$('quality').value=launchQuality;$('quality').onchange();if($('launchQuality'))$('launchQuality').onchange=e=>{$('quality').value=e.target.value;$('quality').onchange();};
let character=null;window.__spiderReady=Promise.all([lowGraphics?Promise.resolve(null):createCharacter(hero,{lowPoly:lowGraphics}),detail.ready]).then(([c])=>{character=c;$('freeBtn').disabled=$('campaignBtn').disabled=false;$('loading').textContent='Ready to play';if(window.__spiderStartMode){$('launchQuality').disabled=false;start(window.__spiderStartMode);}}).catch(error=>{$('loading').textContent='Character failed to load. Please reload.';console.error(error);throw error;});
let frames=0,lastFrame=-Infinity;function frame(now=0){requestAnimationFrame(frame);if(lowGraphics&&now-lastFrame<32)return;lastFrame=now;if(lowGraphics&&frames%15===0)updateNearbyCity();const dt=Math.min(clock.getDelta(),.05);if(mode==='menu'){time+=dt;hero.position.set(90,145,80);hero.rotation.set(-.2,time*.12,0);arms[0].pivot.rotation.z=-2.5;arms[1].pivot.rotation.z=1.2;legs[0].pivot.rotation.x=.5;legs[1].pivot.rotation.x=-.6;legs[0].joint.rotation.x=1.1;legs[1].joint.rotation.x=.5;camera.position.set(93+Math.sin(time*.05)*.7,146.8,86+Math.cos(time*.05));camera.lookAt(89,146.2,80);updateNPCs(0);}
else if(!paused){time+=dt;accum+=dt;while(accum>=1/120){physics(1/120);accum-=1/120;}animateHero(dt);passenger.visible=!!(mission&&mode==='campaign'&&mission.type==='rescue'&&(!completeDelay||rescued.rescueState==='safe'));if(passenger.visible){if(!rescued.event){if(player.carrying){rescued.p.copy(player.p).add(new V(-Math.sin(player.yaw)*.5,.48,-Math.cos(player.yaw)*.5));rescued.dir=player.yaw;}else if(rescued.rescueState==='waiting')rescued.p.copy(mission.p);}if(rescued.rescueState==='safe')rescued.safeAge+=dt;passenger.position.copy(rescued.p);passenger.rotation.set(0,0,0);detail.posePerson(passengerRig,rescued,time,false);}updateCamera(dt);updateNPCs(dt);updateBossHUD();updateMission(dt);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0;}if(frames%5===0){selectedAnchor=findAnchor();$('speed').textContent=Math.round(player.v.length()*3.6);$('altitude').textContent=Math.round(player.p.y)+' m altitude';$('healthFill').style.width=player.hp+'%';$('district').textContent=player.p.x>1200?'EAST WATERFRONT':player.p.z<-800?'NORTH HEIGHTS':player.p.x<-700?'OLD TOWN':player.p.z>850?'RESIDENTIAL':'MIDTOWN';minimap();}if(selectedAnchor&&!player.anchor){let pt=selectedAnchor.clone().project(camera);$('anchor').style.display=pt.z<1&&Math.abs(pt.x)<.95&&Math.abs(pt.y)<.9?'block':'none';$('anchor').style.left=((pt.x+1)*innerWidth/2-17)+'px';$('anchor').style.top=((-pt.y+1)*innerHeight/2-17)+'px';}else $('anchor').style.display='none';$('prompt').textContent=player.carrying?'Passenger secured · C at street level':player.anchor?'Release SPACE to launch':!selectedAnchor&&!player.ground?'No anchor above · steer toward a taller building':'';}
if(windGain)windGain.gain.value=mode!=='menu'&&!paused&&$('sound').checked?Math.min(player.v.length()/500,.16):0;
for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.t-=paused?0:dt;e.mesh.material.opacity=e.t/e.max;if(e.t<=0){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1);}}
for(let i=0;i<cars.length;i++){let c=cars[i];if(!paused)c.z+=dt*c.speed;if(c.z>2230)c.z=-2230;dummy.position.set(c.x,1,c.z);dummy.rotation.set(0,0,0);dummy.scale.set(2.6,1.1,5.3);dummy.updateMatrix();carBody.setMatrixAt(i,dummy.matrix);dummy.position.y=1.8;dummy.scale.set(2.3,.8,2.8);dummy.updateMatrix();carTop.setMatrixAt(i,dummy.matrix);}carBody.instanceMatrix.needsUpdate=carTop.instanceMatrix.needsUpdate=true;
if(character){character.update(paused?0:dt,player,time,mode==='menu');if(player.anchor&&mode!=='menu'){const wrist=character.getSwingGrip();ropeGeo.attributes.position.setXYZ(0,wrist.x,wrist.y,wrist.z);ropeGeo.attributes.position.needsUpdate=true;ropeGeo.computeBoundingSphere();}}detail.update(time,$('quality').value);sky.position.copy(camera.position);sun.position.copy(player.p).add(new V(-400,650,-500));sun.target.position.copy(player.p);heroLight.position.copy(camera.position).add(new V(1,3,2));heroLight.target.position.copy(hero.position).add(new V(0,1.3,0));renderer.render(scene,camera);frames++;}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'start_game_mode',description:'Start the visible Spider-Man game in campaign or free-roam mode.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['free','campaign']}},required:['mode'],additionalProperties:false},execute(input){if(!input||!['free','campaign'].includes(input.mode))throw Error('Choose free or campaign');start(input.mode);return{mode,mission:mission?.title??null};}});}catch{}}
window.__game={updateNearbyCity,staticBatches,bosses,campaign,defeatBoss,bossAttack,updateBossHUD,getDefeatedBosses:()=>[...defeatedBosses],collision,supportHeight,spawnNPC,director,rescued,enemyAttack,updateNPCs,getCharacter:()=>character,detail,player,buildings,npcs,start,physics,animateHero,findAnchor,attach,attack,loadMission,updateMission,setMissionIndex:i=>missionIndex=i,getMission:()=>mission,getState:()=>({mode,paused,mission:mission?.title,missionIndex,position:player.p.toArray(),speed:player.v.length(),anchor:!!player.anchor,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles})};frame();
