import * as T from './vendor/three.module.js';
export async function loadPopulationSurface(lowPoly=false){const response=await fetch(new URL(lowPoly?'./models/population-low.pack':'./models/population-surface.pack',import.meta.url));if(!response.ok)throw Error('Population surface unavailable');const buffer=await new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer(),header=new Uint32Array(buffer,0,2),count=header[0],geo=new T.BufferGeometry();let offset=8;for(const[name,size,Type]of[['position',3,Float32Array],['normal',3,Float32Array],['skinIndex',4,Uint16Array],['skinWeight',4,Float32Array]]){const a=new Type(buffer,offset,count*size);geo.setAttribute(name,new T.BufferAttribute(a,size));offset+=a.byteLength;}geo.setIndex(new T.BufferAttribute(new Uint32Array(buffer,offset,header[1]),1));geo.setAttribute('restPosition',geo.attributes.position.clone());geo.computeVertexNormals();return geo;}
export function installPopulationSurface(p,geometry){const nodes=[p.root,p.limbs[0],p.elbows[0],p.limbs[1],p.knees[0],p.limbs[2],p.elbows[1],p.limbs[3],p.knees[1]],saved=nodes.map(n=>({n,p:n.position.clone(),q:n.quaternion.clone(),s:n.scale.clone()}));p.root.position.set(0,0,0);p.root.scale.setScalar(1);for(const n of nodes)n.quaternion.identity();p.root.updateMatrixWorld(true);const skeleton=new T.Skeleton(nodes),palette={cloth:{value:new T.Color()},skin:{value:new T.Color()},pants:{value:new T.Color()},shoe:{value:new T.Color('#151a21')}};const material=new T.MeshStandardMaterial({roughness:.62,metalness:.05});material.userData.palette=palette;material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,palette);shader.vertexShader='attribute vec3 restPosition;varying vec3 bodyP;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nbodyP=restPosition;');shader.fragmentShader='varying vec3 bodyP;uniform vec3 cloth;uniform vec3 skin;uniform vec3 pants;uniform vec3 shoe;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
vec3 base=bodyP.y<.88?pants:cloth;
if(bodyP.y<.13)base=shoe;
if(bodyP.y>1.49||(abs(bodyP.x)>.27&&bodyP.y<.765))base=skin;
float thread=sin(bodyP.y*1600.)*sin(bodyP.x*1600.)*.026;
diffuseColor.rgb*=base*(1.+thread);
`);};material.customProgramCacheKey=()=> 'population-cloth-v1';const mesh=new T.SkinnedMesh(geometry,material);mesh.frustumCulled=false;mesh.castShadow=mesh.receiveShadow=true;p.root.add(mesh);mesh.bind(skeleton,new T.Matrix4());p.surface=mesh;for(const o of p.bodyMeshes)o.visible=false;for(const a of saved){a.n.position.copy(a.p);a.n.quaternion.copy(a.q);a.n.scale.copy(a.s);}p.root.updateMatrixWorld(true);return mesh;}
