import {Simulation,PROTOCOL} from './simulation.js';
const $=id=>document.getElementById(id);
export async function createBattle(bridge,weapons){
 const [world,config]=await Promise.all([fetch('./world.json').then(r=>r.json()),fetch('./config.json').then(r=>r.json())]);
 const b={active:false,menu:true,sim:null,ws:null,id:null,owner:null,snapshot:null,code:'',seq:0,accum:0,lastAccount:-1,lastReceived:0,connected:false};
 const panel=document.createElement('section');panel.id='match-menu';panel.className='modal visible';panel.innerHTML=`<div class="eyebrow">NORTHLINE / OPERATIONS</div><h2>CHOOSE YOUR DEPLOYMENT</h2><p>Free-for-all combat across Blackpine and Old Town.</p><div class="match-fields"><label>Operator name<input id="operator-name" maxlength="20" value="Operator"></label><label>AI opponents<input id="bot-count" type="number" min="0" max="12" value="4"></label><label>AI difficulty<select id="ai-difficulty"><option>easy</option><option selected>normal</option><option>hard</option></select></label><label>Maximum health<input id="match-health" type="number" min="25" max="300" value="100"></label><label>Regeneration / second<input id="match-regen" type="number" min="0" max="25" value="0"></label><label>Round minutes<input id="match-minutes" type="number" min="1" max="30" value="10"></label></div><p>Regeneration starts after 5 seconds without damage. Settings apply to solo and newly created private rooms.</p><div class="match-actions"><button id="play-solo">1 · SOLO VS AI</button><button id="play-public">2 · PUBLIC SERVER</button><button id="create-private">3 · CREATE PRIVATE ROOM</button></div><div class="join-row"><input id="join-code" maxlength="6" inputmode="numeric" placeholder="Six-digit join code" aria-label="Join code"><button id="join-private">4 · JOIN ROOM</button></div><p id="connection-status" role="status">Loading server configuration…</p><details><summary>Custom server</summary><label>Server URL<input id="server-url" placeholder="https://your-service.onrender.com"></label><p>Use your deployed Northline server, or localhost during development.</p></details><div id="room-panel" hidden><h3 id="room-code"></h3><div id="room-roster"></div><button id="start-room">ENTER · START MATCH</button></div><div class="match-actions"><button id="resume-match" hidden>ESC · RESUME</button><button id="leave-match" hidden>LEAVE MATCH</button><button id="preview-mode">5 · MAP / ANIMATION PREVIEW</button><a href="./arsenal.html" style="padding:15px;color:#efc69a">WEAPON GALLERY ↗</a></div>`;document.body.append(panel);
 const overlay=document.createElement('div');overlay.innerHTML='<div id="combat-hud" hidden><div id="match-clock"></div><div id="health-text"></div><div id="health-track"><i id="health-fill"></i></div><small>F5 MATCH MENU · F6 SCOREBOARD</small></div><button id="match-menu-button">F5 · MATCHES</button><div id="kill-feed"></div><div id="hit-marker">×</div><div id="damage-direction"></div><div id="respawn-message"></div><section id="scoreboard" class="modal"><h2>ROUND STANDINGS</h2><div id="score-rows"></div><p id="score-status"></p><button id="play-again">ENTER · PLAY AGAIN</button><button id="score-menu">F5 · MATCH MENU</button></section>';document.body.append(overlay);
 try{$('operator-name').value=localStorage.getItem('northline-name')||'Operator';$('server-url').value=config.serverUrl||localStorage.getItem('northline-server')||((location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.hostname.endsWith('.onrender.com'))?location.origin:'');}catch{}
 const status=t=>$('connection-status').textContent=t;
 status($('server-url').value?'Server configured. Choose a mode to deploy.':'Solo is ready. Online modes need a deployed server URL.');
 const settings=()=>({bots:+$('bot-count').value,health:+$('match-health').value,regen:+$('match-regen').value,minutes:+$('match-minutes').value,difficulty:$('ai-difficulty').value});
 const name=()=>{const n=$('operator-name').value||'Operator';try{localStorage.setItem('northline-name',n);}catch{}return n;};
 b.canPlay=()=>!b.menu&&(!b.active||b.snapshot?.phase==='playing'&&!b.snapshot.players.find(p=>p.id===b.id)?.dead);
 b.showMenu=(yes=true)=>{b.menu=yes;panel.classList.toggle('visible',yes);if(yes)bridge.release();$('resume-match').hidden=!b.active||b.snapshot?.phase!=='playing';$('leave-match').hidden=!b.active;};
 b.leave=()=>{b.active=false;b.connected=false;const ws=b.ws;b.ws=null;ws?.close();b.sim=null;b.id=null;b.snapshot=null;b.lastAccount=-1;bridge.clear();$('room-panel').hidden=true;$('combat-hud').hidden=true;$('scoreboard').classList.remove('visible');$('respawn-message').textContent='';document.body.classList.remove('in-match');b.showMenu();};
 b.command=c=>{if(!b.active)return false;if(b.sim){const r=b.sim.command(b.id,c);if(c.type!=='shot'||!r.ok)bridge.account(b.sim.account(b.sim.players.get(b.id)));if(!r.ok)bridge.notify(r.reason||'Action unavailable');return r.ok;}if(b.connected&&b.ws?.readyState===WebSocket.OPEN){b.ws.send(JSON.stringify({type:'command',seq:++b.seq,command:c}));return true;}return false;};
 b.accept=(s,events=[])=>{const prev=b.snapshot;b.snapshot=s;b.lastReceived=performance.now();const me=s.players.find(p=>p.id===b.id);if(!me)return;bridge.snapshot(s,b.id,!prev||prev.phase!==s.phase||prev.players.find(p=>p.id===b.id)?.dead&&!me.dead);$('combat-hud').hidden=false;document.body.classList.add('in-match');if(s.phase==='playing'&&prev?.phase!=='playing'){b.showMenu(false);$('room-panel').hidden=true;$('scoreboard').classList.remove('visible');}if(s.phase==='ended'){document.exitPointerLock?.();$('scoreboard').classList.add('visible');$('play-again').hidden=b.code==='PUBLIC'||(b.ws&&b.owner!==b.id);$('score-status').textContent=b.code==='PUBLIC'?'Next round starts automatically.':b.ws&&b.owner!==b.id?'Waiting for the host to start the next round.':'Round complete.';}
 const sec=Math.ceil(s.remaining);$('match-clock').textContent=(b.sim?'SOLO':b.code==='PUBLIC'?'PUBLIC':'ROOM '+b.code)+' · '+Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');$('health-text').textContent=Math.ceil(me.hp)+' HP · '+me.kills+' K / '+me.deaths+' D'+(me.protected?' · SPAWN SHIELD':'');$('health-fill').style.width=(me.hp/s.settings.health*100)+'%';$('respawn-message').textContent=me.dead?'RESPAWNING IN '+Math.ceil(me.respawnIn):'';$('injury').style.opacity=me.dead?'.8':String(Math.max(0,(1-me.hp/s.settings.health)*.7));
 const rows=$('score-rows');rows.replaceChildren();for(const p of [...s.players].sort((a,c)=>c.kills-a.kills||a.deaths-c.deaths)){const row=document.createElement('div');row.className='score-row';for(const val of [p.name+(p.bot?' [AI]':p.id===b.id?' [YOU]':''),p.kills+' K',p.deaths+' D']){const span=document.createElement('span');span.textContent=val;row.append(span);}rows.append(row);}
 for(const e of events){bridge.event(e,s,b.id);if(e.type==='kill'){const line=document.createElement('div');line.textContent=e.killer+' → '+e.name;$('kill-feed').prepend(line);setTimeout(()=>line.remove(),5000);}if(e.type==='shot'&&e.id===b.id&&e.hit){$('hit-marker').classList.add('show');setTimeout(()=>$('hit-marker').classList.remove('show'),120);}if(e.type==='hurt'&&e.id===b.id){const attacker=s.players.find(p=>p.id===e.by);if(attacker){const angle=Math.atan2(attacker.x-me.x,-(attacker.z-me.z))+me.yaw;$('damage-direction').style.transform='translate(-50%,-50%) rotate('+angle+'rad)';$('damage-direction').classList.add('show');setTimeout(()=>$('damage-direction').classList.remove('show'),850);}}}
 };
 b.solo=()=>{b.leave();b.active=true;b.id='local';b.code='SOLO';b.sim=new Simulation(weapons,world,settings());b.sim.addPlayer(b.id,name());b.sim.start();bridge.account(b.sim.account(b.sim.players.get(b.id)));b.accept(b.sim.snapshot(),b.sim.drain());bridge.begin();};
 b.connect=kind=>{const value=$('server-url').value.trim();let url;try{url=new URL(value);if(!['http:','https:','ws:','wss:'].includes(url.protocol))throw 0;if(location.protocol==='https:'&&['http:','ws:'].includes(url.protocol))throw 0;url.protocol=url.protocol==='https:'||url.protocol==='wss:'?'wss:':'ws:';url.pathname='/ws';url.search=url.hash='';}catch{status('Enter a valid HTTPS server URL under Custom server. Solo works without a server.');return;}
 const code=$('join-code').value.trim();if(kind==='join'&&!/^\d{6}$/.test(code)){status('Enter the six-digit code from the room host.');return;}b.leave();status('Connecting…');try{localStorage.setItem('northline-server',value);}catch{}const ws=new WebSocket(url);b.ws=ws;let welcomed=false;const timeout=setTimeout(()=>{if(!welcomed){status('Server did not respond. Check the URL and deployment status.');ws.close();}},12000);ws.onopen=()=>ws.send(JSON.stringify({type:'join',protocol:PROTOCOL,kind,code,name:name(),settings:settings()}));ws.onmessage=message=>{if(b.ws!==ws)return;let m;try{m=JSON.parse(message.data);}catch{return;}if(m.type==='welcome'){welcomed=true;clearTimeout(timeout);b.active=b.connected=true;b.id=m.id;b.code=m.code;b.owner=m.owner;bridge.account(m.account);b.accept(m.snapshot);bridge.begin();status(m.code==='PUBLIC'?'Connected to the public server.':'Connected. Share the room code with friends.');$('leave-match').hidden=false;}if(m.type==='lobby'){b.owner=m.owner;if(b.snapshot?.phase==='lobby'){$('room-panel').hidden=false;$('room-code').textContent='JOIN CODE: '+m.code;$('room-roster').textContent=m.players.map(p=>p.name+(p.id===m.owner?' (host)':'')).join(' · ');$('start-room').hidden=b.id!==m.owner;b.showMenu(true);}}if(m.type==='snapshot')b.accept(m.snapshot,m.events);if(m.account&&m.type!=='welcome')bridge.account(m.account);if(m.type==='error'){status(m.message);ws.close();}if(m.type==='ack'&&!m.ok)bridge.notify(m.message||'Action unavailable');};ws.onerror=()=>status('Could not connect to the server. Check its URL and deployment.');ws.onclose=()=>{clearTimeout(timeout);if(b.ws!==ws)return;b.connected=false;b.active=false;bridge.clear();b.showMenu(true);status(welcomed?'Disconnected from the server. Rejoin to continue.':$('connection-status').textContent==='Connecting…'?'Connection failed. Check the server URL.':$('connection-status').textContent);};};
 b.tick=dt=>{if(!b.active)return;b.accum+=dt;if(b.accum>=.05){const step=Math.min(b.accum,.1);b.accum=0;const input={type:'input',seq:++b.seq,...bridge.input(b.canPlay())};if(b.sim){if(!b.menu){b.sim.input(b.id,input);b.sim.step(step);const p=b.sim.players.get(b.id);if(p.rev!==b.lastAccount){b.lastAccount=p.rev;bridge.account(b.sim.account(p));}b.accept(b.sim.snapshot(),b.sim.drain());}}else if(b.connected){b.ws.send(JSON.stringify(input));if(performance.now()-b.lastReceived>10000){b.ws.close();status('Connection timed out. Rejoin to continue.');}}}bridge.animate(dt,b.snapshot,b.id);};
 $('play-solo').onclick=b.solo;$('play-public').onclick=()=>b.connect('public');$('create-private').onclick=()=>b.connect('create');$('join-private').onclick=()=>b.connect('join');$('start-room').onclick=()=>b.ws?.send(JSON.stringify({type:'start'}));$('leave-match').onclick=b.leave;$('resume-match').onclick=()=>{b.showMenu(false);bridge.capture();};$('preview-mode').onclick=()=>{b.leave();b.showMenu(false);bridge.preview();};$('match-menu-button').onclick=()=>b.showMenu();$('score-menu').onclick=()=>{ $('scoreboard').classList.remove('visible');b.showMenu();};$('play-again').onclick=()=>{if(b.sim)b.solo();else b.ws?.send(JSON.stringify({type:'restart'}));};
 b.key=e=>{if(e.code==='F5'){e.preventDefault();b.showMenu(!b.menu);return true;}if(e.code==='F6'){e.preventDefault();if(b.active)$('scoreboard').classList.toggle('visible');return true;}if(b.menu){if(e.code==='Escape'&&b.snapshot?.phase==='playing')b.showMenu(false);if(!['INPUT','SELECT'].includes(document.activeElement.tagName)&&!e.repeat){if(e.code==='Digit1')b.solo();if(e.code==='Digit2')b.connect('public');if(e.code==='Digit3')b.connect('create');if(e.code==='Digit4')b.connect('join');if(e.code==='Digit5')$('preview-mode').click();if(e.code==='Enter'&&b.owner===b.id)$('start-room').click();}return true;}if(b.active&&b.snapshot?.phase==='ended'){if(e.code==='Enter'&&!$('play-again').hidden)$('play-again').click();return true;}return false;};
 return b;
}
