import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {Simulation}from './simulation.js';
const weapons=JSON.parse(fs.readFileSync(new URL('./weapons.json',import.meta.url))),world=JSON.parse(fs.readFileSync(new URL('./world.json',import.meta.url)));
function setup(settings={}){const s=new Simulation(weapons,{colliders:[],depots:[{x:0,z:0,w:20,d:20}]},{bots:0,...settings});s.addPlayer('a','Alice');s.addPlayer('b','Bob');s.start();const a=s.players.get('a'),b=s.players.get('b');Object.assign(a,{x:0,z:0,y:0,yaw:0,pitch:0,spawnUntil:0});Object.assign(b,{x:0,z:-10,y:0,spawnUntil:0});return{s,a,b};}
const advance=(s,n)=>{for(let i=0;i<n*20;i++)s.step(.05);};
test('bot count and settings are bounded',()=>{const{s}=setup({bots:99,health:999,regen:-2});assert.equal(s.settings.bots,12);assert.equal(s.players.size,14);assert.equal(s.settings.health,300);assert.equal(s.settings.regen,0);});
test('shots consume ammo, damage, score, and respawn',()=>{const{s,a,b}=setup();for(let i=0;i<4;i++){s.command('a',{type:'shot',yaw:0,pitch:0});advance(s,.1);}assert.equal(a.inv.rifle.loaded.rounds,26);assert.equal(b.dead,true);assert.equal(a.kills,1);advance(s,4.1);assert.equal(b.dead,false);assert.equal(b.hp,100);assert.equal(b.deaths,1);});
test('magazine identity, partial rounds, and reload lock survive swaps',()=>{const{s,a}=setup();s.command('a',{type:'shot'});const old={...a.inv.rifle.loaded},spare=a.inv.rifle.reserves[0];assert.equal(s.command('a',{type:'reload',magId:spare.id}).ok,true);assert.equal(s.command('a',{type:'shot'}).ok,false);advance(s,3);assert.equal(a.inv.rifle.loaded.id,spare.id);assert.equal(a.inv.rifle.reserves.find(m=>m.id===old.id).rounds,29);s.command('a',{type:'reload',magId:old.id});advance(s,3);assert.equal(a.inv.rifle.loaded.rounds,29);assert.equal(a.inv.rifle.reserves.length,5);});
test('armory validates position, ownership, money, and two weapon slots',()=>{const{s,a}=setup();assert.equal(s.command('a',{type:'buy',kind:'weapon',weapon:'m82',slot:'primary'}).ok,true);assert.equal(a.cash,5500);assert.equal(a.slots.secondary,'g17');a.x=80;assert.equal(s.command('a',{type:'buy',kind:'armor',value:'heavy'}).ok,false);assert.equal(s.command('a',{type:'equip',weapon:'rpg7',slot:'primary'}).ok,false);});
test('caliber limits penetration and zero-penetration profiles lose against armor',()=>{const{s}=setup();assert.ok(s.ballistics('g17',6).pen<42);assert.ok(s.ballistics('m82',6).pen>90);assert.equal(s.ballistics('rifle',0).pen,0);assert.equal(s.ballistics('rifle',0).damage,2*s.ballistics('rifle',3).damage);});
test('regeneration delay and round restart',()=>{const{s,b}=setup({regen:10,public:true,minutes:1});s.damage(b,30,null);advance(s,4);assert.equal(b.hp,70);advance(s,7);assert.equal(b.hp,100);advance(s,50);assert.equal(s.phase,'ended');advance(s,13);assert.equal(s.phase,'playing');assert.equal(s.round,2);});
test('bots navigate and fire in the production world',()=>{const s=new Simulation(weapons,world,{bots:2});s.addPlayer('a','Human');s.start();const start=[...s.players.values()].filter(p=>p.bot).map(p=>[p.x,p.z]);let shots=0;for(let i=0;i<1200;i++){s.step(.05);shots+=s.drain().filter(e=>e.type==='shot').length;}const bots=[...s.players.values()].filter(p=>p.bot);assert.ok(bots.some((p,i)=>Math.hypot(p.x-start[i][0],p.z-start[i][1])>5));assert.ok(shots>0,'Bots should engage in 60 simulated seconds');});
