// Shared, renderer-free authority: runs in single-player, private-room hosts, or Node.
export const PROTOCOL=1;
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x)),num=(x,d=0)=>Number.isFinite(x)?x:d;
const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t);};
const ARMOR={none:1,light:.95,medium:.9,heavy:.85},RESIST={none:0,light:14,medium:27,heavy:42};
const AMMO=[{d:2,p:0,c:90},{d:1.7,p:.15,c:75},{d:1.4,p:.35,c:65},{d:1,p:.6,c:45},{d:.9,p:.9,c:85},{d:.8,p:1.2,c:115},{d:.7,p:1.55,c:150}];
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const cleanName=x=>String(x||'Operator').replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,20)||'Operator';
function direction(yaw,pitch){return {x:-Math.sin(yaw)*Math.cos(pitch),y:Math.sin(pitch),z:-Math.cos(yaw)*Math.cos(pitch)};}
export class Simulation{
constructor(weapons,world,settings={}){this.weapons=weapons;this.world=world;this.settings={bots:clamp(Math.floor(num(settings.bots,4)),0,12),health:clamp(num(settings.health,100),25,300),regen:clamp(num(settings.regen,0),0,25),minutes:clamp(num(settings.minutes,10),1,30),difficulty:['easy','normal','hard'].includes(settings.difficulty)?settings.difficulty:'normal',public:!!settings.public,maxPlayers:settings.public?8:4};this.players=new Map();this.events=[];this.projectiles=[];this.time=0;this.round=1;this.phase='lobby';this.deadline=0;this.serial=0;this.projectileSerial=0;this.navCache=new Map();this.destroyed=[];}
height(x,z){const edge=Math.max(smooth(54,78,-x),smooth(54,78,-z));let h=Math.max(0,edge*(2+9*Math.exp(-((x+90)**2+(z+40)**2)/1300)+14*Math.exp(-((x+7)**2+(z+94)**2)/1400)+3*Math.sin(x*.044)*Math.cos(z*.038)));h*=1-smooth(42,65,x);for(const d of this.world.depots)h*=smooth(13,26,Math.hypot(x-d.x,z-d.z));return h*smooth(0,9,Math.abs(z-39));}
blocked(x,z,y=this.height(x,z)){return Math.abs(x)>117.4||Math.abs(z)>117.4||this.world.colliders.some(c=>x>c.minX&&x<c.maxX&&z>c.minZ&&z<c.maxZ&&y<c.top&&y+1.7>c.bottom);}
mag(weapon,type=3){return{id:++this.serial,weapon,type,rounds:this.weapons[weapon].capacity};}
loadout(weapon,n=2){return{loaded:this.mag(weapon),reserves:Array.from({length:n},()=>this.mag(weapon))};}
spawnPoint(p){const locations=[[2,7],[-9,33],[20,34],[78,28],[78,-40],[-80,35],[-78,-55],[-12,-65],[105,58],[-87,85],[-47,51],[45,46]];const enemies=[...this.players.values()].filter(a=>a.id!==p.id&&!a.dead);let best=null,score=-1;for(let i=0;i<locations.length;i++){const [x,z]=locations[(i+this.round)%locations.length];if(this.blocked(x,z))continue;const d=enemies.length?Math.min(...enemies.map(e=>Math.hypot(x-e.x,z-e.z))):Math.random()*20;if(d>score){best={x,z};score=d;}}return best||{x:2,z:7};}
addPlayer(id,name,bot=false){if(this.players.has(id))return this.players.get(id);const p={id,name:cleanName(name),bot,x:2,y:0,z:7,yaw:0,pitch:0,hp:this.settings.health,dead:false,kills:0,deaths:0,cash:12000,slots:{primary:'rifle',secondary:'g17'},activeSlot:'primary',weapon:'rifle',armor:'none',ownedArmor:['none'],ownedOptics:['reflex'],scope:'reflex',grip:false,hasGrip:false,grenades:2,inv:{rifle:this.loadout('rifle',5),g17:this.loadout('g17',3)},input:{},inputAt:0,lastSeq:-1,lastShot:-10,lastHit:-10,reloadUntil:0,pending:null,respawnAt:0,spawnUntil:0,jumpY:0,vy:0,rev:1,path:[],planAt:0,thinkAt:0,burstAt:0,action:'Idle',actionUntil:0};this.players.set(id,p);this.respawn(p,true);return p;}
removePlayer(id){this.players.delete(id);}
respawn(p,initial=false){const point=this.spawnPoint(p);p.x=point.x;p.z=point.z;p.y=this.height(p.x,p.z);p.yaw=Math.atan2(p.x,p.z);p.pitch=0;p.hp=this.settings.health;p.dead=false;p.jumpY=p.vy=0;p.spawnUntil=this.time+3;p.reloadUntil=0;p.pending=null;p.path=[];p.input={};if(!initial){for(const [id,v]of Object.entries(p.inv)){v.loaded=this.mag(id);v.reserves=[this.mag(id),this.mag(id)];}p.grenades=Math.max(1,p.grenades);p.cash+=250;p.rev++;}this.events.push({type:'respawn',id:p.id});}
start(){if(this.phase==='playing')return;this.phase='playing';this.deadline=this.time+this.settings.minutes*60;for(const p of [...this.players.values()])if(p.bot)this.players.delete(p.id);for(let i=0;i<this.settings.bots;i++)this.addPlayer('bot'+i,['Rook','Viper','Warden','Echo','Kestrel','Fox','Lancer','Ghost','Aster','Stone','Atlas','Hawk'][i],true);for(const p of this.players.values()){p.kills=p.deaths=0;this.respawn(p,true);}this.events.push({type:'start',round:this.round});}
restart(){this.round++;this.phase='lobby';this.start();}
nearDepot(p){return this.world.depots.some(d=>Math.abs(p.x-d.x)<d.w/2+2&&Math.abs(p.z-d.z)<d.d/2+3);}
input(id,data){const p=this.players.get(id);if(!p||p.bot||p.dead||this.phase!=='playing')return;const seq=num(data.seq,-1);if(seq<=p.lastSeq)return;p.lastSeq=seq;p.inputAt=this.time;p.yaw=num(data.yaw,p.yaw);p.pitch=clamp(num(data.pitch,p.pitch),-1.3,1.3);p.input={forward:clamp(num(data.forward),-1,1),strafe:clamp(num(data.strafe),-1,1),sprint:!!data.sprint,crouch:!!data.crouch,aim:!!data.aim};if(data.jump&&p.jumpY===0)p.vy=5.1;}
account(p){return {id:p.id,cash:p.cash,slots:{...p.slots},activeSlot:p.activeSlot,weapon:p.weapon,armor:p.armor,ownedArmor:[...p.ownedArmor],ownedOptics:[...p.ownedOptics],scope:p.scope,grip:p.grip,hasGrip:p.hasGrip,grenades:p.grenades,inv:JSON.parse(JSON.stringify(p.inv)),rev:p.rev,reloadRemaining:Math.max(0,p.reloadUntil-this.time),pending:p.pending?{...p.pending}:null};}
command(id,c){const p=this.players.get(id);if(!p||p.dead||this.phase!=='playing')return{ok:false,reason:'Not alive in an active match'};if(!c||typeof c!=='object')return{ok:false};if(c.type==='shot'){if(Number.isFinite(c.yaw))p.yaw=c.yaw;if(Number.isFinite(c.pitch))p.pitch=clamp(c.pitch,-1.3,1.3);return this.shoot(p);}
if(c.type==='reload'){if(p.reloadUntil>this.time)return{ok:false,reason:'Already reloading'};const inv=p.inv[p.weapon];let at=inv.reserves.findIndex(m=>m.id===c.magId&&m.rounds>0);if(at<0)return{ok:false,reason:'Magazine unavailable'};p.pending=inv.reserves.splice(at,1)[0];p.reloadUntil=this.time+2.8;p.action='Reload';p.rev++;return{ok:true};}
if(c.type==='equip'){if(p.reloadUntil>this.time||!Object.hasOwn(p.inv,c.weapon)||!['primary','secondary'].includes(c.slot))return{ok:false,reason:'Cannot equip this weapon'};const other=c.slot==='primary'?'secondary':'primary';if(p.slots[other]===c.weapon)p.slots[other]=p.slots[c.slot];p.slots[c.slot]=c.weapon;p.activeSlot=c.slot;p.weapon=c.weapon;p.rev++;return{ok:true};}
if(c.type==='configure'){if(p.ownedArmor.includes(c.armor))p.armor=c.armor;if(p.ownedOptics.includes(c.scope))p.scope=c.scope;if(p.hasGrip)p.grip=!!c.grip;p.rev++;return{ok:true};}
if(c.type==='grenade'){if(p.grenades<1)return{ok:false,reason:'No grenades'};p.grenades--;p.action='Grenade';p.actionUntil=this.time+2.3;p.rev++;this.projectile(p,'grenade');return{ok:true};}
if(c.type==='melee'){if(this.time-p.lastMelee<1.1)return{ok:false};p.lastMelee=this.time;p.action='Melee';p.actionUntil=this.time+1.1;for(const q of this.players.values())if(q!==p&&!q.dead&&distance(p,q)<1.7&&this.lineClear({x:p.x,y:p.y+1.2,z:p.z},{x:q.x,y:q.y+1.2,z:q.z}))this.damage(q,35,p);return{ok:true};}
if(c.type==='buy'){if(!this.nearDepot(p)||p.reloadUntil>this.time)return{ok:false,reason:'Enter an armory and finish reloading first'};if(['ammo','bundle'].includes(c.kind)&&p.inv[p.weapon].reserves.length>=100)return{ok:false,reason:'Magazine inventory full'};let cost=0,apply=()=>{};const w=this.weapons[p.weapon],factor=w.category==='Pistols'||w.category==='SMGs'?.7:w.category==='Assault rifles'?1:1.35;
if(c.kind==='weapon'){const d=this.weapons[c.weapon];if(!Object.hasOwn(this.weapons,c.weapon)||!['primary','secondary'].includes(c.slot))return{ok:false};cost=p.inv[c.weapon]?0:d.price;apply=()=>{if(!Object.hasOwn(p.inv,c.weapon))p.inv[c.weapon]=this.loadout(c.weapon);const other=c.slot==='primary'?'secondary':'primary';if(p.slots[other]===c.weapon)p.slots[other]=p.slots[c.slot];p.slots[c.slot]=c.weapon;p.activeSlot=c.slot;p.weapon=c.weapon;};}
else if(c.kind==='ammo'){const type=clamp(Math.floor(num(c.ammo,3)),0,6);if(w.category==='Launchers'&&type!==3)return{ok:false};cost=w.category==='Launchers'?350:Math.round(AMMO[type].c*factor);apply=()=>p.inv[p.weapon].reserves.push(this.mag(p.weapon,type));}
else if(c.kind==='bundle'){cost=w.category==='Launchers'?950:Math.round(120*factor);apply=()=>{for(let i=0;i<3;i++)p.inv[p.weapon].reserves.push(this.mag(p.weapon));};}
else if(c.kind==='armor'&&Object.hasOwn(ARMOR,c.value)){cost=p.ownedArmor.includes(c.value)?0:({none:0,light:350,medium:750,heavy:1250})[c.value];apply=()=>{if(!p.ownedArmor.includes(c.value))p.ownedArmor.push(c.value);p.armor=c.value;};}
else if(c.kind==='optic'&&['reflex','scope'].includes(c.value)){cost=p.ownedOptics.includes(c.value)?0:850;apply=()=>{if(!p.ownedOptics.includes(c.value))p.ownedOptics.push(c.value);p.scope=c.value;};}
else if(c.kind==='grip'){cost=p.hasGrip?0:250;apply=()=>{p.hasGrip=true;p.grip=!p.grip;};}
else if(c.kind==='grenade'){cost=250;apply=()=>p.grenades++;}else return{ok:false,reason:'Unknown purchase'};
if(p.cash<cost)return{ok:false,reason:'Not enough cash'};p.cash-=cost;apply();p.rev++;return{ok:true};}
return{ok:false,reason:'Unknown command'};}
rayBox(o,d,c,limit){let lo=0,hi=limit;for(const [k,min,max]of [['x',c.minX+.24,c.maxX-.24],['y',c.bottom,c.top],['z',c.minZ+.24,c.maxZ-.24]]){if(Math.abs(d[k])<1e-7){if(o[k]<min||o[k]>max)return null;}else{let a=(min-o[k])/d[k],b=(max-o[k])/d[k];if(a>b)[a,b]=[b,a];lo=Math.max(lo,a);hi=Math.min(hi,b);if(lo>hi)return null;}}return lo>=0&&lo<=limit?lo:null;}
wallDistance(o,d,limit=200){let nearest=limit;for(const c of this.world.colliders){const n=this.rayBox(o,d,c,nearest);if(n!==null)nearest=n;}return nearest;}
lineClear(a,b){const len=Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z);if(len<.01)return true;return this.wallDistance(a,{x:(b.x-a.x)/len,y:(b.y-a.y)/len,z:(b.z-a.z)/len},len)>=len-.05;}
raySphere(o,d,c,r){const x=o.x-c.x,y=o.y-c.y,z=o.z-c.z,b=x*d.x+y*d.y+z*d.z,disc=b*b-(x*x+y*y+z*z-r*r);if(disc<0)return null;const n=-b-Math.sqrt(disc);return n>=0?n:null;}
// Vertical capsule covers legs, torso and shoulders without gaps between spheres.
rayCapsule(o,d,x,z,bottom,top,r){
let nearest=null;const ox=o.x-x,oz=o.z-z,a=d.x*d.x+d.z*d.z,b=ox*d.x+oz*d.z,c=ox*ox+oz*oz-r*r;
if(a>1e-8){const disc=b*b-a*c;if(disc>=0){for(const t of [(-b-Math.sqrt(disc))/a,(-b+Math.sqrt(disc))/a]){const y=o.y+d.y*t;if(t>=0&&y>=bottom&&y<=top&&(nearest===null||t<nearest))nearest=t;}}}
for(const y of [bottom,top]){const t=this.raySphere(o,d,{x,y,z},r);if(t!==null&&(nearest===null||t<nearest))nearest=t;}
return nearest;}
ballistics(weapon,ammo=3){const w=this.weapons[weapon],c=w.caliber;let damage=34,pen=32;if(c.includes('9×')){damage=25;pen=13;}if(c.includes('.45')){damage=31;pen=14;}if(c.includes('4.6')||c.includes('5.7')){damage=23;pen=21;}if(c.includes('7.62')){damage=47;pen=45;}if(c.includes('.50 AE')){damage=62;pen=26;}if(c.includes('.338')){damage=95;pen=67;}if(c.includes('.50 BMG')){damage=135;pen=95;}if(w.category==='Shotguns'){damage=13;pen=14;}return{damage:damage*AMMO[ammo].d,pen:pen*AMMO[ammo].p};}
shoot(p){const w=this.weapons[p.weapon],inv=p.inv[p.weapon];if(p.reloadUntil>this.time||this.time-p.lastShot<w.interval-.025||inv.loaded.rounds<=0)return{ok:false,reason:'Weapon is not ready'};p.lastShot=this.time;inv.loaded.rounds--;p.action='Fire';p.actionUntil=this.time+.16;const source={x:p.x,y:p.y+(p.input.crouch?1.22:1.68),z:p.z};if(w.category==='Launchers'){this.projectile(p,p.weapon==='m79'?'shell':'rocket');return{ok:true};}const pellets=w.category==='Shotguns'?7:1;let hits=0;for(let i=0;i<pellets;i++){let dir=direction(p.yaw,p.pitch);if(pellets>1){dir.x+=(Math.random()-.5)*.045;dir.y+=(Math.random()-.5)*.045;const n=Math.hypot(dir.x,dir.y,dir.z);dir={x:dir.x/n,y:dir.y/n,z:dir.z/n};}let target=null,range=180,head=false;for(const q of this.players.values()){if(q===p||q.dead)continue;const crouched=!!q.input.crouch;const body=this.rayCapsule(source,dir,q.x,q.z,q.y+.32,q.y+(crouched?.88:1.27),.29),headHit=this.raySphere(source,dir,{x:q.x,y:q.y+(crouched?1.22:1.64),z:q.z},.20);for(const [n,isHead]of [[body,false],[headHit,true]]){if(n!==null&&n<range){range=n;target=q;head=isHead;}}}const ball=this.ballistics(p.weapon,inv.loaded.type);let energy=1,wall=this.wallDistance(source,dir,range);if(wall<range-.01){let layers=0;for(const c of this.world.colliders){const n=this.rayBox(source,dir,c,range);if(n!==null){const thickness=Math.min(c.maxX-c.minX,c.maxZ-c.minZ);const resistance=thickness>2?90:thickness>1?65:45;if(ball.pen<resistance){energy=0;range=Math.min(range,n);break;}energy*=.55;if(++layers>2){energy=0;break;}}}}if(target&&energy>0){let dmg=ball.damage*energy*Math.max(.55,1-range/500)*(head?1.65:1);if(!head&&target.armor!=='none')dmg*=ball.pen>=RESIST[target.armor]?.82:.09;if(this.damage(target,dmg,p))hits++;}if(i===0)this.events.push({type:'shot',id:p.id,from:source,to:{x:source.x+dir.x*range,y:source.y+dir.y*range,z:source.z+dir.z*range},hit:hits>0});}return{ok:true};}
projectile(p,kind){const dir=direction(p.yaw,p.pitch),speed=kind==='rocket'?75:kind==='shell'?25:12;this.projectiles.push({id:++this.projectileSerial,owner:p.id,kind,x:p.x+dir.x*.8,y:p.y+1.5,z:p.z+dir.z*.8,vx:dir.x*speed,vy:dir.y*speed+(kind==='grenade'?3:0),vz:dir.z*speed,life:kind==='rocket'?4:2.8});}
damage(p,amount,killer){if(p.dead||this.time<p.spawnUntil)return false;p.hp=Math.max(0,p.hp-amount);p.lastHit=this.time;this.events.push({type:'hurt',id:p.id,by:killer?.id,hp:p.hp});if(p.hp<=0){p.dead=true;p.deaths++;p.respawnAt=this.time+4;p.action='Death';p.actionUntil=p.respawnAt;if(killer&&killer!==p){killer.kills++;killer.cash+=500;killer.rev++;}this.events.push({type:'kill',id:p.id,by:killer?.id,name:p.name,killer:killer?.name||'Explosion'});}return true;}
explode(projectile){this.events.push({type:'blast',x:projectile.x,y:projectile.y,z:projectile.z,kind:projectile.kind});const owner=this.players.get(projectile.owner),radius=projectile.kind==='rocket'?7:6;for(const p of this.players.values()){if(p.dead)continue;const d=Math.hypot(p.x-projectile.x,p.y+.8-projectile.y,p.z-projectile.z);if(d<radius&&this.lineClear({x:projectile.x,y:projectile.y+.1,z:projectile.z},{x:p.x,y:p.y+1,z:p.z}))this.damage(p,(projectile.kind==='rocket'?300:170)*(1-d/radius),owner);}}
segmentClear(x,z,nx,nz){const n=Math.max(1,Math.ceil(Math.hypot(nx-x,nz-z)/.8));for(let i=1;i<=n;i++){const a=x+(nx-x)*i/n,b=z+(nz-z)*i/n;if(this.blocked(a,b))return false;}return true;}
path(x,z,tx,tz){const S=4,N=59,key=(a,b)=>a+b*N,to=v=>clamp(Math.round((v+116)/S),0,N-1),pos=k=>({x:(k%N)*S-116,z:Math.floor(k/N)*S-116}),start=key(to(x),to(z)),goal=key(to(tx),to(tz)),open=[start],came=new Map(),g=new Map([[start,0]]),closed=new Set();let found=start;const heuristic=k=>{const p=pos(k);return Math.hypot(p.x-tx,p.z-tz)/S;};for(let n=0;n<900&&open.length;n++){open.sort((a,b)=>(g.get(a)+heuristic(a))-(g.get(b)+heuristic(b)));const k=open.shift();if(closed.has(k))continue;closed.add(k);if(heuristic(k)<heuristic(found))found=k;if(k===goal||heuristic(k)<1.5){found=k;break;}const a=pos(k),ix=k%N,iz=Math.floor(k/N);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){const xx=ix+dx,zz=iz+dz;if(xx<0||xx>=N||zz<0||zz>=N)continue;const nk=key(xx,zz);if(closed.has(nk))continue;const b=pos(nk),cache=k<nk?k+':'+nk:nk+':'+k;let pass=this.navCache.get(cache);if(pass===undefined){pass=this.segmentClear(a.x,a.z,b.x,b.z);this.navCache.set(cache,pass);}if(!pass)continue;const cost=g.get(k)+Math.hypot(dx,dz);if(cost<(g.get(nk)??Infinity)){g.set(nk,cost);came.set(nk,k);open.push(nk);}}}const result=[];for(let k=found;k!==start&&came.has(k);k=came.get(k))result.unshift(pos(k));return result;}
bot(p,dt){const enemies=[...this.players.values()].filter(q=>q!==p&&!q.dead);if(!enemies.length)return;enemies.sort((a,b)=>distance(p,a)-distance(p,b));const target=enemies[0],d=distance(p,target),eye={x:p.x,y:p.y+1.55,z:p.z},aim={x:target.x,y:target.y+1.1,z:target.z};const visible=d<95&&this.lineClear(eye,aim);p.input={};if(visible){const dx=aim.x-eye.x,dz=aim.z-eye.z;p.yaw=Math.atan2(-dx,-dz);p.pitch=Math.atan2(aim.y-eye.y,Math.hypot(dx,dz));const diff=this.settings.difficulty,spread=diff==='easy'?.085:diff==='hard'?.012:.036;if(this.time>=p.thinkAt){p.yaw+=(Math.random()-.5)*spread;p.pitch+=(Math.random()-.5)*spread;p.thinkAt=this.time+(diff==='easy'?.38:diff==='hard'?.13:.22);this.shoot(p);}if(d>27){p.input.forward=1;p.input.sprint=true;}else if(d<9)p.input.forward=-1;else p.input.strafe=Math.sin(this.time*.9+p.id.length)>0?.45:-.45;p.action=p.reloadUntil>this.time?'Reload':'Aim';}else{if(this.time>p.planAt||!p.path.length){p.path=this.path(p.x,p.z,target.x,target.z);p.planAt=this.time+2+Math.random();}const point=p.path[0];if(point){if(Math.hypot(point.x-p.x,point.z-p.z)<1)p.path.shift();else{p.yaw=Math.atan2(p.x-point.x,p.z-point.z);p.input.forward=1;p.input.sprint=true;}}}
const inv=p.inv[p.weapon];if(inv.loaded.rounds===0&&p.reloadUntil<=this.time){if(!inv.reserves.some(m=>m.rounds>0))inv.reserves.push(this.mag(p.weapon));this.command(p.id,{type:'reload',magId:inv.reserves.find(m=>m.rounds>0).id});}}
step(dt){dt=clamp(dt,0,.1);this.time+=dt;if(this.phase==='ended'){if(this.settings.public&&this.time>this.restartAt)this.restart();return;}if(this.phase!=='playing')return;if(this.time>=this.deadline){this.phase='ended';this.restartAt=this.time+12;this.events.push({type:'end'});return;}
for(const p of this.players.values()){if(p.dead){if(this.time>=p.respawnAt)this.respawn(p);continue;}if(p.reloadUntil&&this.time>=p.reloadUntil){const inv=p.inv[p.weapon];inv.reserves.push(inv.loaded);inv.loaded=p.pending;p.pending=null;p.reloadUntil=0;p.rev++;}if(this.settings.regen&&this.time-p.lastHit>5)p.hp=Math.min(this.settings.health,p.hp+this.settings.regen*dt);if(p.bot)this.bot(p,dt);else if(this.time-p.inputAt>.4)p.input={};const i=p.input,forward=num(i.forward),strafe=num(i.strafe),len=Math.max(1,Math.hypot(forward,strafe)),speed=(i.crouch?1.7:i.sprint&&!i.aim?6.8:3.7)*ARMOR[p.armor];let dx=(-Math.sin(p.yaw)*forward+Math.cos(p.yaw)*strafe)/len*speed*dt,dz=(-Math.cos(p.yaw)*forward-Math.sin(p.yaw)*strafe)/len*speed*dt;const nx=p.x+dx,nz=p.z+dz;if(!this.blocked(nx,p.z,this.height(nx,p.z)+p.jumpY))p.x=nx;if(!this.blocked(p.x,nz,this.height(p.x,nz)+p.jumpY))p.z=nz;if(p.vy||p.jumpY){p.vy-=13.8*dt;p.jumpY+=p.vy*dt;if(p.jumpY<0)p.jumpY=p.vy=0;}p.y=this.height(p.x,p.z)+p.jumpY;if(p.reloadUntil>this.time)p.action='Reload';else if(this.time>p.actionUntil)p.action=p.jumpY?'Jump':i.crouch?'Crouch':i.aim?'Aim':forward||strafe?(i.sprint?'Sprint':'Walk'):'Idle';}
for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i],o={x:p.x,y:p.y,z:p.z},len=Math.hypot(p.vx,p.vy,p.vz)*dt,dir={x:p.vx*dt/len,y:p.vy*dt/len,z:p.vz*dt/len},wall=this.wallDistance(o,dir,len);p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.life-=dt;p.vy-=(p.kind==='rocket'?0:12)*dt;if(wall<len||p.y<this.height(p.x,p.z)+.06){if(p.kind==='grenade'){p.y=Math.max(this.height(p.x,p.z)+.08,p.y);p.vy=Math.abs(p.vy)*.35;p.vx*=.6;p.vz*=.6;}else p.life=0;}if(p.kind!=='grenade')for(const q of this.players.values())if(q.id!==p.owner&&!q.dead&&Math.hypot(q.x-p.x,q.y+1-p.y,q.z-p.z)<.7)p.life=0;if(p.life<=0){this.explode(p);this.projectiles.splice(i,1);}}}
snapshot(){return{protocol:PROTOCOL,phase:this.phase,time:this.time,remaining:Math.max(0,this.deadline-this.time),round:this.round,settings:this.settings,players:[...this.players.values()].map(p=>({id:p.id,name:p.name,bot:p.bot,x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,hp:p.hp,dead:p.dead,kills:p.kills,deaths:p.deaths,weapon:p.weapon,armor:p.armor,action:p.action,respawnIn:Math.max(0,p.respawnAt-this.time),protected:this.time<p.spawnUntil})),projectiles:this.projectiles.map(p=>({id:p.id,kind:p.kind,x:p.x,y:p.y,z:p.z,vx:p.vx,vy:p.vy,vz:p.vz}))};}
drain(){const events=this.events;this.events=[];return events;}
}
