import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath}from'node:url';import{WebSocketServer,WebSocket}from'ws';import{Simulation,PROTOCOL}from'../simulation.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),weapons=JSON.parse(fs.readFileSync(path.join(root,'weapons.json'))),world=JSON.parse(fs.readFileSync(path.join(root,'world.json'))),rooms=new Map();let nextId=0;
const room=(code,settings={})=>{const r={code,sim:new Simulation(weapons,world,settings),sockets:new Map(),owner:null,lastActive:Date.now()};rooms.set(code,r);return r;};const publicRoom=room('PUBLIC',{public:true,bots:4,minutes:10});publicRoom.sim.start();
const mime={'.css':'text/css','.html':'text/html','.js':'application/javascript','.json':'application/json','.glb':'model/gltf-binary','.txt':'text/plain'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');res.setHeader('Access-Control-Allow-Origin','*');if(url.pathname==='/health'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:true,protocol:PROTOCOL,publicPlayers:publicRoom.sockets.size,publicBots:publicRoom.sim.settings.bots,round:publicRoom.sim.round,uptime:process.uptime()}));return;}let decoded;try{decoded=decodeURIComponent(url.pathname);}catch{res.writeHead(400);res.end('Invalid path');return;}let rel=decoded.replace(/^\/northline\//,'').replace(/^\//,'')||'index.html';const file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||rel.startsWith('server/')){res.writeHead(403);res.end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);res.end('Not found');return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(data);});});
const wss=new WebSocketServer({server,path:'/ws',maxPayload:16384});const send=(s,m)=>{if(s.readyState===WebSocket.OPEN&&s.bufferedAmount<512000)s.send(JSON.stringify(m));};
function sendRoster(r){const m={type:'lobby',code:r.code,owner:r.owner,players:[...r.sim.players.values()].filter(p=>!p.bot).map(p=>({id:p.id,name:p.name})),settings:r.sim.settings};for(const s of r.sockets.values())send(s,m);}
wss.on('connection',socket=>{let joined=null,id=null,count=0,windowAt=Date.now();const deadline=setTimeout(()=>socket.close(1008,'Join required'),15000);socket.on('message',raw=>{if(Date.now()-windowAt>1000){count=0;windowAt=Date.now();}if(++count>100){socket.close(1008,'Rate limit');return;}let m;try{m=JSON.parse(raw);}catch{return;}if(!m||typeof m!=='object')return;
if(!joined){if(m.type!=='join'||m.protocol!==PROTOCOL){send(socket,{type:'error',message:'Client/server version mismatch'});return;}let r;if(m.kind==='public')r=publicRoom;else if(m.kind==='create'){if(rooms.size>=32){send(socket,{type:'error',message:'Server room capacity reached'});return;}let code;do{code=String(Math.floor(100000+Math.random()*900000));}while(rooms.has(code));r=room(code,m.settings||{});}else r=rooms.get(String(m.code));if(!r||r.sim.phase!=='lobby'&&r!==publicRoom){send(socket,{type:'error',message:'Room not found or already playing'});return;}if(r.sockets.size>=r.sim.settings.maxPlayers){send(socket,{type:'error',message:'Room is full'});return;}clearTimeout(deadline);joined=r;id='p'+(++nextId);r.sockets.set(id,socket);r.owner??=id;const p=r.sim.addPlayer(id,m.name);r.lastActive=Date.now();send(socket,{type:'welcome',id,code:r.code,owner:r.owner,account:r.sim.account(p),snapshot:r.sim.snapshot()});sendRoster(r);return;}
const r=joined,p=r.sim.players.get(id);if(!p)return;r.lastActive=Date.now();if(m.type==='input')r.sim.input(id,m);else if(m.type==='command'){const result=r.sim.command(id,m.command);send(socket,{type:'ack',seq:m.seq,ok:result.ok,message:result.reason,account:(!result.ok||m.command?.type!=='shot')?r.sim.account(p):undefined});}else if(m.type==='start'&&id===r.owner&&r!==publicRoom&&r.sim.phase==='lobby'){r.sim.start();}else if(m.type==='restart'&&id===r.owner&&r!==publicRoom&&r.sim.phase==='ended')r.sim.restart();});socket.on('close',()=>{clearTimeout(deadline);if(!joined)return;joined.sockets.delete(id);joined.sim.removePlayer(id);if(joined.owner===id){joined.owner=joined.sockets.keys().next().value||null;}sendRoster(joined);});socket.on('error',()=>{});});
let last=performance.now(),accum=0,snapshotTick=0;setInterval(()=>{const now=performance.now();accum+=Math.min(.2,(now-last)/1000);last=now;while(accum>=.05){for(const r of rooms.values())r.sim.step(.05);accum-=.05;}if(++snapshotTick%2===0){for(const r of rooms.values()){const snapshot=r.sim.snapshot(),events=r.sim.drain();for(const[id,s]of r.sockets){send(s,{type:'snapshot',snapshot,events});const p=r.sim.players.get(id);if(p&&s._rev!==p.rev){s._rev=p.rev;send(s,{type:'account',account:r.sim.account(p)});}}if(r!==publicRoom&&!r.sockets.size&&Date.now()-r.lastActive>300000)rooms.delete(r.code);}}},25);
server.listen(process.env.PORT||8787,'0.0.0.0',()=>console.log('Northline server ready on '+(process.env.PORT||8787)));process.on('SIGTERM',()=>{for(const s of wss.clients)s.close(1001,'Server restarting');server.close(()=>process.exit(0));});
